package com.asg.domain.repository;

import com.asg.domain.model.TmAccesshin;
import com.asg.domain.model.TmAccesshinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmAccesshinRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    long countByExample(TmAccesshinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int deleteByExample(TmAccesshinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cdAccesshin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int insert(TmAccesshin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int insertSelective(TmAccesshin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    List<TmAccesshin> selectByExampleWithRowbounds(TmAccesshinExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    List<TmAccesshin> selectByExample(TmAccesshinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    TmAccesshin selectByPrimaryKey(String cdAccesshin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmAccesshin record, @Param("example") TmAccesshinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmAccesshin record, @Param("example") TmAccesshinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmAccesshin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmAccesshin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmAccesshin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSHIN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmAccesshin record);
}