package com.asg.domain.repository;

import com.asg.domain.model.TmAccessshu;
import com.asg.domain.model.TmAccessshuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmAccessshuRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    long countByExample(TmAccessshuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int deleteByExample(TmAccessshuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cdAccessshu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int insert(TmAccessshu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int insertSelective(TmAccessshu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    List<TmAccessshu> selectByExampleWithRowbounds(TmAccessshuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    List<TmAccessshu> selectByExample(TmAccessshuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    TmAccessshu selectByPrimaryKey(String cdAccessshu);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmAccessshu record, @Param("example") TmAccessshuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmAccessshu record, @Param("example") TmAccessshuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmAccessshu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmAccessshu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmAccessshu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmAccessshu record);
}