package com.asg.domain.repository;

import com.asg.domain.model.TmGroup;
import com.asg.domain.model.TmGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmGroupRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    long countByExample(TmGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int deleteByExample(TmGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("cdKaisha") String cdKaisha, @Param("cdGroup") String cdGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int insert(TmGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int insertSelective(TmGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    List<TmGroup> selectByExampleWithRowbounds(TmGroupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    List<TmGroup> selectByExample(TmGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    TmGroup selectByPrimaryKey(@Param("cdKaisha") String cdKaisha, @Param("cdGroup") String cdGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmGroup record, @Param("example") TmGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmGroup record, @Param("example") TmGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmGroup record);
}