package com.asg.domain.repository;

import com.asg.domain.model.TmGrShozoku;
import com.asg.domain.model.TmGrShozokuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmGrShozokuRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    long countByExample(TmGrShozokuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int deleteByExample(TmGrShozokuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("cdKaisha") String cdKaisha, @Param("cdGroup") String cdGroup, @Param("cdUser") String cdUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int insert(TmGrShozoku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int insertSelective(TmGrShozoku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    List<TmGrShozoku> selectByExampleWithRowbounds(TmGrShozokuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    List<TmGrShozoku> selectByExample(TmGrShozokuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    TmGrShozoku selectByPrimaryKey(@Param("cdKaisha") String cdKaisha, @Param("cdGroup") String cdGroup, @Param("cdUser") String cdUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmGrShozoku record, @Param("example") TmGrShozokuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmGrShozoku record, @Param("example") TmGrShozokuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmGrShozoku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmGrShozoku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmGrShozoku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_GR_SHOZOKU
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmGrShozoku record);
}