package com.asg.domain.repository;

import com.asg.domain.model.TmKaisha;
import com.asg.domain.model.TmKaishaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmKaishaRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    long countByExample(TmKaishaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int deleteByExample(TmKaishaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cdKaisha);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int insert(TmKaisha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int insertSelective(TmKaisha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    List<TmKaisha> selectByExampleWithRowbounds(TmKaishaExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    List<TmKaisha> selectByExample(TmKaishaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    TmKaisha selectByPrimaryKey(String cdKaisha);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmKaisha record, @Param("example") TmKaishaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmKaisha record, @Param("example") TmKaishaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmKaisha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmKaisha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmKaisha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmKaisha record);
}