package com.asg.domain.repository;

import com.asg.domain.model.TmKen;
import com.asg.domain.model.TmKenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmKenRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    long countByExample(TmKenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int deleteByExample(TmKenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cdKen);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int insert(TmKen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int insertSelective(TmKen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    List<TmKen> selectByExampleWithRowbounds(TmKenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    List<TmKen> selectByExample(TmKenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    TmKen selectByPrimaryKey(String cdKen);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmKen record, @Param("example") TmKenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmKen record, @Param("example") TmKenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmKen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmKen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmKen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmKen record);
}