package com.asg.domain.repository;

import com.asg.domain.model.TmMailKanri;
import com.asg.domain.model.TmMailKanriExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmMailKanriRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    long countByExample(TmMailKanriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int deleteByExample(TmMailKanriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("cdKsJtKyu") String cdKsJtKyu, @Param("cdKoshinshaKaisha") String cdKoshinshaKaisha, @Param("cdHozon") String cdHozon, @Param("cdJtShiji") String cdJtShiji, @Param("cdKsJtShin") String cdKsJtShin, @Param("cdMlJun") String cdMlJun);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int insert(TmMailKanri record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int insertSelective(TmMailKanri record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    List<TmMailKanri> selectByExampleWithRowbounds(TmMailKanriExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    List<TmMailKanri> selectByExample(TmMailKanriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    TmMailKanri selectByPrimaryKey(@Param("cdKsJtKyu") String cdKsJtKyu, @Param("cdKoshinshaKaisha") String cdKoshinshaKaisha, @Param("cdHozon") String cdHozon, @Param("cdJtShiji") String cdJtShiji, @Param("cdKsJtShin") String cdKsJtShin, @Param("cdMlJun") String cdMlJun);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmMailKanri record, @Param("example") TmMailKanriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmMailKanri record, @Param("example") TmMailKanriExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmMailKanri record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmMailKanri record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmMailKanri record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmMailKanri record);
}