package com.asg.domain.repository;

import com.asg.domain.model.TmRolepermission;
import com.asg.domain.model.TmRolepermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmRolepermissionRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    long countByExample(TmRolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int deleteByExample(TmRolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("cdRole") String cdRole, @Param("cdPermission") String cdPermission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int insert(TmRolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int insertSelective(TmRolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    List<TmRolepermission> selectByExampleWithRowbounds(TmRolepermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    List<TmRolepermission> selectByExample(TmRolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    TmRolepermission selectByPrimaryKey(@Param("cdRole") String cdRole, @Param("cdPermission") String cdPermission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmRolepermission record, @Param("example") TmRolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmRolepermission record, @Param("example") TmRolepermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmRolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmRolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmRolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmRolepermission record);
}