package com.asg.domain.repository;

import com.asg.domain.model.TmUser;
import com.asg.domain.model.TmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmUserRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    long countByExample(TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int deleteByExample(TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cdUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int insert(TmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int insertSelective(TmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    List<TmUser> selectByExampleWithRowbounds(TmUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    List<TmUser> selectByExample(TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    TmUser selectByPrimaryKey(Integer cdUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TmUser record, @Param("example") TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TmUser record, @Param("example") TmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TmUser record);
}