package com.asg.domain.repository;

import com.asg.domain.model.TtKenmei;
import com.asg.domain.model.TtKenmeiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TtKenmeiRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    long countByExample(TtKenmeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int deleteByExample(TtKenmeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cdKenmei);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int insert(TtKenmei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int insertSelective(TtKenmei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    List<TtKenmei> selectByExampleWithRowbounds(TtKenmeiExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    List<TtKenmei> selectByExample(TtKenmeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    TtKenmei selectByPrimaryKey(String cdKenmei);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TtKenmei record, @Param("example") TtKenmeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TtKenmei record, @Param("example") TtKenmeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TtKenmei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TtKenmei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TtKenmei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TtKenmei record);
}