package com.asg.domain.repository;

import com.asg.domain.model.TtKijo;
import com.asg.domain.model.TtKijoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TtKijoRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    long countByExample(TtKijoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int deleteByExample(TtKijoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("cdKenmei") String cdKenmei, @Param("cdKaisen") String cdKaisen);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int insert(TtKijo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int insertSelective(TtKijo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    List<TtKijo> selectByExampleWithRowbounds(TtKijoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    List<TtKijo> selectByExample(TtKijoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    TtKijo selectByPrimaryKey(@Param("cdKenmei") String cdKenmei, @Param("cdKaisen") String cdKaisen);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TtKijo record, @Param("example") TtKijoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TtKijo record, @Param("example") TtKijoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdatedSelective(TtKijo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TtKijo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndLastUpdated(TtKijo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TtKijo record);
}