package com.asg.domain.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TmAccessshuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public TmAccessshuExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCdAccessshuIsNull() {
            addCriterion("CD_ACCESSSHU is null");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuIsNotNull() {
            addCriterion("CD_ACCESSSHU is not null");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuEqualTo(String value) {
            addCriterion("CD_ACCESSSHU =", value, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuNotEqualTo(String value) {
            addCriterion("CD_ACCESSSHU <>", value, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuGreaterThan(String value) {
            addCriterion("CD_ACCESSSHU >", value, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ACCESSSHU >=", value, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuLessThan(String value) {
            addCriterion("CD_ACCESSSHU <", value, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuLessThanOrEqualTo(String value) {
            addCriterion("CD_ACCESSSHU <=", value, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuLike(String value) {
            addCriterion("CD_ACCESSSHU like", value, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuNotLike(String value) {
            addCriterion("CD_ACCESSSHU not like", value, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuIn(List<String> values) {
            addCriterion("CD_ACCESSSHU in", values, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuNotIn(List<String> values) {
            addCriterion("CD_ACCESSSHU not in", values, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuBetween(String value1, String value2) {
            addCriterion("CD_ACCESSSHU between", value1, value2, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andCdAccessshuNotBetween(String value1, String value2) {
            addCriterion("CD_ACCESSSHU not between", value1, value2, "cdAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuIsNull() {
            addCriterion("KJ_ACCESSSHU is null");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuIsNotNull() {
            addCriterion("KJ_ACCESSSHU is not null");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuEqualTo(String value) {
            addCriterion("KJ_ACCESSSHU =", value, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuNotEqualTo(String value) {
            addCriterion("KJ_ACCESSSHU <>", value, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuGreaterThan(String value) {
            addCriterion("KJ_ACCESSSHU >", value, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuGreaterThanOrEqualTo(String value) {
            addCriterion("KJ_ACCESSSHU >=", value, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuLessThan(String value) {
            addCriterion("KJ_ACCESSSHU <", value, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuLessThanOrEqualTo(String value) {
            addCriterion("KJ_ACCESSSHU <=", value, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuLike(String value) {
            addCriterion("KJ_ACCESSSHU like", value, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuNotLike(String value) {
            addCriterion("KJ_ACCESSSHU not like", value, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuIn(List<String> values) {
            addCriterion("KJ_ACCESSSHU in", values, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuNotIn(List<String> values) {
            addCriterion("KJ_ACCESSSHU not in", values, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuBetween(String value1, String value2) {
            addCriterion("KJ_ACCESSSHU between", value1, value2, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andKjAccessshuNotBetween(String value1, String value2) {
            addCriterion("KJ_ACCESSSHU not between", value1, value2, "kjAccessshu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuIsNull() {
            addCriterion("NM_JORETSU is null");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuIsNotNull() {
            addCriterion("NM_JORETSU is not null");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuEqualTo(Integer value) {
            addCriterion("NM_JORETSU =", value, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuNotEqualTo(Integer value) {
            addCriterion("NM_JORETSU <>", value, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuGreaterThan(Integer value) {
            addCriterion("NM_JORETSU >", value, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuGreaterThanOrEqualTo(Integer value) {
            addCriterion("NM_JORETSU >=", value, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuLessThan(Integer value) {
            addCriterion("NM_JORETSU <", value, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuLessThanOrEqualTo(Integer value) {
            addCriterion("NM_JORETSU <=", value, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuIn(List<Integer> values) {
            addCriterion("NM_JORETSU in", values, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuNotIn(List<Integer> values) {
            addCriterion("NM_JORETSU not in", values, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuBetween(Integer value1, Integer value2) {
            addCriterion("NM_JORETSU between", value1, value2, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andNmJoretsuNotBetween(Integer value1, Integer value2) {
            addCriterion("NM_JORETSU not between", value1, value2, "nmJoretsu");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIsNull() {
            addCriterion("CD_TEISHI is null");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIsNotNull() {
            addCriterion("CD_TEISHI is not null");
            return (Criteria) this;
        }

        public Criteria andCdTeishiEqualTo(String value) {
            addCriterion("CD_TEISHI =", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotEqualTo(String value) {
            addCriterion("CD_TEISHI <>", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiGreaterThan(String value) {
            addCriterion("CD_TEISHI >", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiGreaterThanOrEqualTo(String value) {
            addCriterion("CD_TEISHI >=", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLessThan(String value) {
            addCriterion("CD_TEISHI <", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLessThanOrEqualTo(String value) {
            addCriterion("CD_TEISHI <=", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLike(String value) {
            addCriterion("CD_TEISHI like", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotLike(String value) {
            addCriterion("CD_TEISHI not like", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIn(List<String> values) {
            addCriterion("CD_TEISHI in", values, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotIn(List<String> values) {
            addCriterion("CD_TEISHI not in", values, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiBetween(String value1, String value2) {
            addCriterion("CD_TEISHI between", value1, value2, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotBetween(String value1, String value2) {
            addCriterion("CD_TEISHI not between", value1, value2, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNull() {
            addCriterion("CD_LU_KAISHA is null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNotNull() {
            addCriterion("CD_LU_KAISHA is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaEqualTo(String value) {
            addCriterion("CD_LU_KAISHA =", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotEqualTo(String value) {
            addCriterion("CD_LU_KAISHA <>", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThan(String value) {
            addCriterion("CD_LU_KAISHA >", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_KAISHA >=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThan(String value) {
            addCriterion("CD_LU_KAISHA <", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_KAISHA <=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLike(String value) {
            addCriterion("CD_LU_KAISHA like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotLike(String value) {
            addCriterion("CD_LU_KAISHA not like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIn(List<String> values) {
            addCriterion("CD_LU_KAISHA in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotIn(List<String> values) {
            addCriterion("CD_LU_KAISHA not in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaBetween(String value1, String value2) {
            addCriterion("CD_LU_KAISHA between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotBetween(String value1, String value2) {
            addCriterion("CD_LU_KAISHA not between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNull() {
            addCriterion("CD_LU_USER is null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNotNull() {
            addCriterion("CD_LU_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserEqualTo(String value) {
            addCriterion("CD_LU_USER =", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotEqualTo(String value) {
            addCriterion("CD_LU_USER <>", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThan(String value) {
            addCriterion("CD_LU_USER >", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER >=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThan(String value) {
            addCriterion("CD_LU_USER <", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER <=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLike(String value) {
            addCriterion("CD_LU_USER like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotLike(String value) {
            addCriterion("CD_LU_USER not like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIn(List<String> values) {
            addCriterion("CD_LU_USER in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotIn(List<String> values) {
            addCriterion("CD_LU_USER not in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserBetween(String value1, String value2) {
            addCriterion("CD_LU_USER between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotBetween(String value1, String value2) {
            addCriterion("CD_LU_USER not between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNull() {
            addCriterion("TM_LU is null");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNotNull() {
            addCriterion("TM_LU is not null");
            return (Criteria) this;
        }

        public Criteria andTmLuEqualTo(LocalDateTime value) {
            addCriterion("TM_LU =", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <>", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThan(LocalDateTime value) {
            addCriterion("TM_LU >", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU >=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThan(LocalDateTime value) {
            addCriterion("TM_LU <", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuIn(List<LocalDateTime> values) {
            addCriterion("TM_LU in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotIn(List<LocalDateTime> values) {
            addCriterion("TM_LU not in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU not between", value1, value2, "tmLu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_ACCESSSHU
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}