package com.asg.domain.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TmCodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public TmCodeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCdShuIsNull() {
            addCriterion("CD_SHU is null");
            return (Criteria) this;
        }

        public Criteria andCdShuIsNotNull() {
            addCriterion("CD_SHU is not null");
            return (Criteria) this;
        }

        public Criteria andCdShuEqualTo(String value) {
            addCriterion("CD_SHU =", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuNotEqualTo(String value) {
            addCriterion("CD_SHU <>", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuGreaterThan(String value) {
            addCriterion("CD_SHU >", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuGreaterThanOrEqualTo(String value) {
            addCriterion("CD_SHU >=", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuLessThan(String value) {
            addCriterion("CD_SHU <", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuLessThanOrEqualTo(String value) {
            addCriterion("CD_SHU <=", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuLike(String value) {
            addCriterion("CD_SHU like", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuNotLike(String value) {
            addCriterion("CD_SHU not like", value, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuIn(List<String> values) {
            addCriterion("CD_SHU in", values, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuNotIn(List<String> values) {
            addCriterion("CD_SHU not in", values, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuBetween(String value1, String value2) {
            addCriterion("CD_SHU between", value1, value2, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdShuNotBetween(String value1, String value2) {
            addCriterion("CD_SHU not between", value1, value2, "cdShu");
            return (Criteria) this;
        }

        public Criteria andCdCodeIsNull() {
            addCriterion("CD_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCdCodeIsNotNull() {
            addCriterion("CD_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCdCodeEqualTo(String value) {
            addCriterion("CD_CODE =", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeNotEqualTo(String value) {
            addCriterion("CD_CODE <>", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeGreaterThan(String value) {
            addCriterion("CD_CODE >", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CD_CODE >=", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeLessThan(String value) {
            addCriterion("CD_CODE <", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeLessThanOrEqualTo(String value) {
            addCriterion("CD_CODE <=", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeLike(String value) {
            addCriterion("CD_CODE like", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeNotLike(String value) {
            addCriterion("CD_CODE not like", value, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeIn(List<String> values) {
            addCriterion("CD_CODE in", values, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeNotIn(List<String> values) {
            addCriterion("CD_CODE not in", values, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeBetween(String value1, String value2) {
            addCriterion("CD_CODE between", value1, value2, "cdCode");
            return (Criteria) this;
        }

        public Criteria andCdCodeNotBetween(String value1, String value2) {
            addCriterion("CD_CODE not between", value1, value2, "cdCode");
            return (Criteria) this;
        }

        public Criteria andKjShuIsNull() {
            addCriterion("KJ_SHU is null");
            return (Criteria) this;
        }

        public Criteria andKjShuIsNotNull() {
            addCriterion("KJ_SHU is not null");
            return (Criteria) this;
        }

        public Criteria andKjShuEqualTo(String value) {
            addCriterion("KJ_SHU =", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuNotEqualTo(String value) {
            addCriterion("KJ_SHU <>", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuGreaterThan(String value) {
            addCriterion("KJ_SHU >", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuGreaterThanOrEqualTo(String value) {
            addCriterion("KJ_SHU >=", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuLessThan(String value) {
            addCriterion("KJ_SHU <", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuLessThanOrEqualTo(String value) {
            addCriterion("KJ_SHU <=", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuLike(String value) {
            addCriterion("KJ_SHU like", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuNotLike(String value) {
            addCriterion("KJ_SHU not like", value, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuIn(List<String> values) {
            addCriterion("KJ_SHU in", values, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuNotIn(List<String> values) {
            addCriterion("KJ_SHU not in", values, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuBetween(String value1, String value2) {
            addCriterion("KJ_SHU between", value1, value2, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjShuNotBetween(String value1, String value2) {
            addCriterion("KJ_SHU not between", value1, value2, "kjShu");
            return (Criteria) this;
        }

        public Criteria andKjCodeIsNull() {
            addCriterion("KJ_CODE is null");
            return (Criteria) this;
        }

        public Criteria andKjCodeIsNotNull() {
            addCriterion("KJ_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andKjCodeEqualTo(String value) {
            addCriterion("KJ_CODE =", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeNotEqualTo(String value) {
            addCriterion("KJ_CODE <>", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeGreaterThan(String value) {
            addCriterion("KJ_CODE >", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeGreaterThanOrEqualTo(String value) {
            addCriterion("KJ_CODE >=", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeLessThan(String value) {
            addCriterion("KJ_CODE <", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeLessThanOrEqualTo(String value) {
            addCriterion("KJ_CODE <=", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeLike(String value) {
            addCriterion("KJ_CODE like", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeNotLike(String value) {
            addCriterion("KJ_CODE not like", value, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeIn(List<String> values) {
            addCriterion("KJ_CODE in", values, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeNotIn(List<String> values) {
            addCriterion("KJ_CODE not in", values, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeBetween(String value1, String value2) {
            addCriterion("KJ_CODE between", value1, value2, "kjCode");
            return (Criteria) this;
        }

        public Criteria andKjCodeNotBetween(String value1, String value2) {
            addCriterion("KJ_CODE not between", value1, value2, "kjCode");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1IsNull() {
            addCriterion("DT_JORETSU1 is null");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1IsNotNull() {
            addCriterion("DT_JORETSU1 is not null");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1EqualTo(Integer value) {
            addCriterion("DT_JORETSU1 =", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1NotEqualTo(Integer value) {
            addCriterion("DT_JORETSU1 <>", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1GreaterThan(Integer value) {
            addCriterion("DT_JORETSU1 >", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1GreaterThanOrEqualTo(Integer value) {
            addCriterion("DT_JORETSU1 >=", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1LessThan(Integer value) {
            addCriterion("DT_JORETSU1 <", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1LessThanOrEqualTo(Integer value) {
            addCriterion("DT_JORETSU1 <=", value, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1In(List<Integer> values) {
            addCriterion("DT_JORETSU1 in", values, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1NotIn(List<Integer> values) {
            addCriterion("DT_JORETSU1 not in", values, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1Between(Integer value1, Integer value2) {
            addCriterion("DT_JORETSU1 between", value1, value2, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu1NotBetween(Integer value1, Integer value2) {
            addCriterion("DT_JORETSU1 not between", value1, value2, "dtJoretsu1");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2IsNull() {
            addCriterion("DT_JORETSU2 is null");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2IsNotNull() {
            addCriterion("DT_JORETSU2 is not null");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2EqualTo(Integer value) {
            addCriterion("DT_JORETSU2 =", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2NotEqualTo(Integer value) {
            addCriterion("DT_JORETSU2 <>", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2GreaterThan(Integer value) {
            addCriterion("DT_JORETSU2 >", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2GreaterThanOrEqualTo(Integer value) {
            addCriterion("DT_JORETSU2 >=", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2LessThan(Integer value) {
            addCriterion("DT_JORETSU2 <", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2LessThanOrEqualTo(Integer value) {
            addCriterion("DT_JORETSU2 <=", value, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2In(List<Integer> values) {
            addCriterion("DT_JORETSU2 in", values, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2NotIn(List<Integer> values) {
            addCriterion("DT_JORETSU2 not in", values, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2Between(Integer value1, Integer value2) {
            addCriterion("DT_JORETSU2 between", value1, value2, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtJoretsu2NotBetween(Integer value1, Integer value2) {
            addCriterion("DT_JORETSU2 not between", value1, value2, "dtJoretsu2");
            return (Criteria) this;
        }

        public Criteria andDtText1IsNull() {
            addCriterion("DT_TEXT1 is null");
            return (Criteria) this;
        }

        public Criteria andDtText1IsNotNull() {
            addCriterion("DT_TEXT1 is not null");
            return (Criteria) this;
        }

        public Criteria andDtText1EqualTo(String value) {
            addCriterion("DT_TEXT1 =", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1NotEqualTo(String value) {
            addCriterion("DT_TEXT1 <>", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1GreaterThan(String value) {
            addCriterion("DT_TEXT1 >", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1GreaterThanOrEqualTo(String value) {
            addCriterion("DT_TEXT1 >=", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1LessThan(String value) {
            addCriterion("DT_TEXT1 <", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1LessThanOrEqualTo(String value) {
            addCriterion("DT_TEXT1 <=", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1Like(String value) {
            addCriterion("DT_TEXT1 like", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1NotLike(String value) {
            addCriterion("DT_TEXT1 not like", value, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1In(List<String> values) {
            addCriterion("DT_TEXT1 in", values, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1NotIn(List<String> values) {
            addCriterion("DT_TEXT1 not in", values, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1Between(String value1, String value2) {
            addCriterion("DT_TEXT1 between", value1, value2, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText1NotBetween(String value1, String value2) {
            addCriterion("DT_TEXT1 not between", value1, value2, "dtText1");
            return (Criteria) this;
        }

        public Criteria andDtText2IsNull() {
            addCriterion("DT_TEXT2 is null");
            return (Criteria) this;
        }

        public Criteria andDtText2IsNotNull() {
            addCriterion("DT_TEXT2 is not null");
            return (Criteria) this;
        }

        public Criteria andDtText2EqualTo(String value) {
            addCriterion("DT_TEXT2 =", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2NotEqualTo(String value) {
            addCriterion("DT_TEXT2 <>", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2GreaterThan(String value) {
            addCriterion("DT_TEXT2 >", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2GreaterThanOrEqualTo(String value) {
            addCriterion("DT_TEXT2 >=", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2LessThan(String value) {
            addCriterion("DT_TEXT2 <", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2LessThanOrEqualTo(String value) {
            addCriterion("DT_TEXT2 <=", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2Like(String value) {
            addCriterion("DT_TEXT2 like", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2NotLike(String value) {
            addCriterion("DT_TEXT2 not like", value, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2In(List<String> values) {
            addCriterion("DT_TEXT2 in", values, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2NotIn(List<String> values) {
            addCriterion("DT_TEXT2 not in", values, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2Between(String value1, String value2) {
            addCriterion("DT_TEXT2 between", value1, value2, "dtText2");
            return (Criteria) this;
        }

        public Criteria andDtText2NotBetween(String value1, String value2) {
            addCriterion("DT_TEXT2 not between", value1, value2, "dtText2");
            return (Criteria) this;
        }

        public Criteria andNmNum1IsNull() {
            addCriterion("NM_NUM1 is null");
            return (Criteria) this;
        }

        public Criteria andNmNum1IsNotNull() {
            addCriterion("NM_NUM1 is not null");
            return (Criteria) this;
        }

        public Criteria andNmNum1EqualTo(BigDecimal value) {
            addCriterion("NM_NUM1 =", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1NotEqualTo(BigDecimal value) {
            addCriterion("NM_NUM1 <>", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1GreaterThan(BigDecimal value) {
            addCriterion("NM_NUM1 >", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NM_NUM1 >=", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1LessThan(BigDecimal value) {
            addCriterion("NM_NUM1 <", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("NM_NUM1 <=", value, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1In(List<BigDecimal> values) {
            addCriterion("NM_NUM1 in", values, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1NotIn(List<BigDecimal> values) {
            addCriterion("NM_NUM1 not in", values, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("NM_NUM1 between", value1, value2, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NM_NUM1 not between", value1, value2, "nmNum1");
            return (Criteria) this;
        }

        public Criteria andNmNum2IsNull() {
            addCriterion("NM_NUM2 is null");
            return (Criteria) this;
        }

        public Criteria andNmNum2IsNotNull() {
            addCriterion("NM_NUM2 is not null");
            return (Criteria) this;
        }

        public Criteria andNmNum2EqualTo(BigDecimal value) {
            addCriterion("NM_NUM2 =", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2NotEqualTo(BigDecimal value) {
            addCriterion("NM_NUM2 <>", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2GreaterThan(BigDecimal value) {
            addCriterion("NM_NUM2 >", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NM_NUM2 >=", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2LessThan(BigDecimal value) {
            addCriterion("NM_NUM2 <", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("NM_NUM2 <=", value, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2In(List<BigDecimal> values) {
            addCriterion("NM_NUM2 in", values, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2NotIn(List<BigDecimal> values) {
            addCriterion("NM_NUM2 not in", values, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("NM_NUM2 between", value1, value2, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andNmNum2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NM_NUM2 not between", value1, value2, "nmNum2");
            return (Criteria) this;
        }

        public Criteria andTmDate1IsNull() {
            addCriterion("TM_DATE1 is null");
            return (Criteria) this;
        }

        public Criteria andTmDate1IsNotNull() {
            addCriterion("TM_DATE1 is not null");
            return (Criteria) this;
        }

        public Criteria andTmDate1EqualTo(LocalDateTime value) {
            addCriterion("TM_DATE1 =", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1NotEqualTo(LocalDateTime value) {
            addCriterion("TM_DATE1 <>", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1GreaterThan(LocalDateTime value) {
            addCriterion("TM_DATE1 >", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1GreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_DATE1 >=", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1LessThan(LocalDateTime value) {
            addCriterion("TM_DATE1 <", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1LessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_DATE1 <=", value, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1In(List<LocalDateTime> values) {
            addCriterion("TM_DATE1 in", values, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1NotIn(List<LocalDateTime> values) {
            addCriterion("TM_DATE1 not in", values, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1Between(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_DATE1 between", value1, value2, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate1NotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_DATE1 not between", value1, value2, "tmDate1");
            return (Criteria) this;
        }

        public Criteria andTmDate2IsNull() {
            addCriterion("TM_DATE2 is null");
            return (Criteria) this;
        }

        public Criteria andTmDate2IsNotNull() {
            addCriterion("TM_DATE2 is not null");
            return (Criteria) this;
        }

        public Criteria andTmDate2EqualTo(LocalDateTime value) {
            addCriterion("TM_DATE2 =", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2NotEqualTo(LocalDateTime value) {
            addCriterion("TM_DATE2 <>", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2GreaterThan(LocalDateTime value) {
            addCriterion("TM_DATE2 >", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2GreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_DATE2 >=", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2LessThan(LocalDateTime value) {
            addCriterion("TM_DATE2 <", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2LessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_DATE2 <=", value, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2In(List<LocalDateTime> values) {
            addCriterion("TM_DATE2 in", values, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2NotIn(List<LocalDateTime> values) {
            addCriterion("TM_DATE2 not in", values, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2Between(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_DATE2 between", value1, value2, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andTmDate2NotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_DATE2 not between", value1, value2, "tmDate2");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIsNull() {
            addCriterion("CD_TEISHI is null");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIsNotNull() {
            addCriterion("CD_TEISHI is not null");
            return (Criteria) this;
        }

        public Criteria andCdTeishiEqualTo(String value) {
            addCriterion("CD_TEISHI =", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotEqualTo(String value) {
            addCriterion("CD_TEISHI <>", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiGreaterThan(String value) {
            addCriterion("CD_TEISHI >", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiGreaterThanOrEqualTo(String value) {
            addCriterion("CD_TEISHI >=", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLessThan(String value) {
            addCriterion("CD_TEISHI <", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLessThanOrEqualTo(String value) {
            addCriterion("CD_TEISHI <=", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiLike(String value) {
            addCriterion("CD_TEISHI like", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotLike(String value) {
            addCriterion("CD_TEISHI not like", value, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiIn(List<String> values) {
            addCriterion("CD_TEISHI in", values, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotIn(List<String> values) {
            addCriterion("CD_TEISHI not in", values, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiBetween(String value1, String value2) {
            addCriterion("CD_TEISHI between", value1, value2, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdTeishiNotBetween(String value1, String value2) {
            addCriterion("CD_TEISHI not between", value1, value2, "cdTeishi");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNull() {
            addCriterion("CD_LU_KAISHA is null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNotNull() {
            addCriterion("CD_LU_KAISHA is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaEqualTo(String value) {
            addCriterion("CD_LU_KAISHA =", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotEqualTo(String value) {
            addCriterion("CD_LU_KAISHA <>", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThan(String value) {
            addCriterion("CD_LU_KAISHA >", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_KAISHA >=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThan(String value) {
            addCriterion("CD_LU_KAISHA <", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_KAISHA <=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLike(String value) {
            addCriterion("CD_LU_KAISHA like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotLike(String value) {
            addCriterion("CD_LU_KAISHA not like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIn(List<String> values) {
            addCriterion("CD_LU_KAISHA in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotIn(List<String> values) {
            addCriterion("CD_LU_KAISHA not in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaBetween(String value1, String value2) {
            addCriterion("CD_LU_KAISHA between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotBetween(String value1, String value2) {
            addCriterion("CD_LU_KAISHA not between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNull() {
            addCriterion("CD_LU_USER is null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNotNull() {
            addCriterion("CD_LU_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserEqualTo(String value) {
            addCriterion("CD_LU_USER =", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotEqualTo(String value) {
            addCriterion("CD_LU_USER <>", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThan(String value) {
            addCriterion("CD_LU_USER >", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER >=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThan(String value) {
            addCriterion("CD_LU_USER <", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER <=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLike(String value) {
            addCriterion("CD_LU_USER like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotLike(String value) {
            addCriterion("CD_LU_USER not like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIn(List<String> values) {
            addCriterion("CD_LU_USER in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotIn(List<String> values) {
            addCriterion("CD_LU_USER not in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserBetween(String value1, String value2) {
            addCriterion("CD_LU_USER between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotBetween(String value1, String value2) {
            addCriterion("CD_LU_USER not between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNull() {
            addCriterion("TM_LU is null");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNotNull() {
            addCriterion("TM_LU is not null");
            return (Criteria) this;
        }

        public Criteria andTmLuEqualTo(LocalDateTime value) {
            addCriterion("TM_LU =", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <>", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThan(LocalDateTime value) {
            addCriterion("TM_LU >", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU >=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThan(LocalDateTime value) {
            addCriterion("TM_LU <", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuIn(List<LocalDateTime> values) {
            addCriterion("TM_LU in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotIn(List<LocalDateTime> values) {
            addCriterion("TM_LU not in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU not between", value1, value2, "tmLu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_CODE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_CODE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}