package com.asg.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TM_GROUP
 */
@Data
public class TmGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_GROUP.CD_KAISHA
     *
     * @mbg.generated
     */
    private String cdKaisha;

    /**
     * Database Column Remarks:
     *   グループID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_GROUP.CD_GROUP
     *
     * @mbg.generated
     */
    private String cdGroup;

    /**
     * Database Column Remarks:
     *   グループ名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_GROUP.KJ_GROUP
     *
     * @mbg.generated
     */
    private String kjGroup;

    /**
     * Database Column Remarks:
     *   使用停止区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_GROUP.CD_TEISHI
     *
     * @mbg.generated
     */
    private String cdTeishi;

    /**
     * Database Column Remarks:
     *   最終更新会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_GROUP.CD_LU_KAISHA
     *
     * @mbg.generated
     */
    private String cdLuKaisha;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_GROUP.CD_LU_USER
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_GROUP.TM_LU
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * Database Column Remarks:
     *   作成ユーザーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_GROUP.CD_CREATE_USER
     *
     * @mbg.generated
     */
    private Integer cdCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_GROUP
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}