package com.asg.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TM_KAISHA
 */
@Data
public class TmKaisha implements Serializable {
    /**
     * Database Column Remarks:
     *   会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.CD_KAISHA
     *
     * @mbg.generated
     */
    private String cdKaisha;

    /**
     * Database Column Remarks:
     *   会社名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.KJ_KAISHA
     *
     * @mbg.generated
     */
    private String kjKaisha;

    /**
     * Database Column Remarks:
     *   会社区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.CD_KAISHA_KB
     *
     * @mbg.generated
     */
    private String cdKaishaKb;

    /**
     * Database Column Remarks:
     *   ロール一覧
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.CD_ROLE_LIST
     *
     * @mbg.generated
     */
    private String cdRoleList;

    /**
     * Database Column Remarks:
     *   件名ID対象コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.CD_KENMEI1
     *
     * @mbg.generated
     */
    private String cdKenmei1;

    /**
     * Database Column Remarks:
     *   件名ID発行年度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.NM_KENMEINEN
     *
     * @mbg.generated
     */
    private Short nmKenmeinen;

    /**
     * Database Column Remarks:
     *   最終件名ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.NM_LASTKENMEI
     *
     * @mbg.generated
     */
    private Integer nmLastkenmei;

    /**
     * Database Column Remarks:
     *   内部件名ID発行年度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.NM_NAIBUNEN
     *
     * @mbg.generated
     */
    private Short nmNaibunen;

    /**
     * Database Column Remarks:
     *   最終内部件名ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.NM_LASTNAIBU
     *
     * @mbg.generated
     */
    private Integer nmLastnaibu;

    /**
     * Database Column Remarks:
     *   最終グループID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.NM_GROUP
     *
     * @mbg.generated
     */
    private Integer nmGroup;

    /**
     * Database Column Remarks:
     *   共通メールアカウント
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.DT_ML_KYOTSU
     *
     * @mbg.generated
     */
    private String dtMlKyotsu;

    /**
     * Database Column Remarks:
     *   使用停止区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.CD_TEISHI
     *
     * @mbg.generated
     */
    private String cdTeishi;

    /**
     * Database Column Remarks:
     *   最終更新会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.CD_LU_KAISHA
     *
     * @mbg.generated
     */
    private String cdLuKaisha;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.CD_LU_USER
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KAISHA.TM_LU
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_KAISHA
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}