package com.asg.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TM_KEN
 */
@Data
public class TmKen implements Serializable {
    /**
     * Database Column Remarks:
     *   都道府県コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.CD_KEN
     *
     * @mbg.generated
     */
    private String cdKen;

    /**
     * Database Column Remarks:
     *   都道府県名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.KJ_KEN
     *
     * @mbg.generated
     */
    private String kjKen;

    /**
     * Database Column Remarks:
     *   対象地域系会社コード１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.CD_KAISHA1
     *
     * @mbg.generated
     */
    private String cdKaisha1;

    /**
     * Database Column Remarks:
     *   対象地域系会社コード２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.CD_KAISHA2
     *
     * @mbg.generated
     */
    private String cdKaisha2;

    /**
     * Database Column Remarks:
     *   序列１
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.NM_JORETSU1
     *
     * @mbg.generated
     */
    private Short nmJoretsu1;

    /**
     * Database Column Remarks:
     *   序列２
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.NM_JORETSU2
     *
     * @mbg.generated
     */
    private Short nmJoretsu2;

    /**
     * Database Column Remarks:
     *   最終更新会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.CD_LU_KAISHA
     *
     * @mbg.generated
     */
    private String cdLuKaisha;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.CD_LU_USER
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_KEN.TM_LU
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_KEN
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}