package com.asg.domain.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TmMailKanriExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public TmMailKanriExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCdKsJtKyuIsNull() {
            addCriterion("CD_KS_JT_KYU is null");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuIsNotNull() {
            addCriterion("CD_KS_JT_KYU is not null");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuEqualTo(String value) {
            addCriterion("CD_KS_JT_KYU =", value, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuNotEqualTo(String value) {
            addCriterion("CD_KS_JT_KYU <>", value, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuGreaterThan(String value) {
            addCriterion("CD_KS_JT_KYU >", value, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuGreaterThanOrEqualTo(String value) {
            addCriterion("CD_KS_JT_KYU >=", value, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuLessThan(String value) {
            addCriterion("CD_KS_JT_KYU <", value, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuLessThanOrEqualTo(String value) {
            addCriterion("CD_KS_JT_KYU <=", value, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuLike(String value) {
            addCriterion("CD_KS_JT_KYU like", value, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuNotLike(String value) {
            addCriterion("CD_KS_JT_KYU not like", value, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuIn(List<String> values) {
            addCriterion("CD_KS_JT_KYU in", values, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuNotIn(List<String> values) {
            addCriterion("CD_KS_JT_KYU not in", values, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuBetween(String value1, String value2) {
            addCriterion("CD_KS_JT_KYU between", value1, value2, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKsJtKyuNotBetween(String value1, String value2) {
            addCriterion("CD_KS_JT_KYU not between", value1, value2, "cdKsJtKyu");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaIsNull() {
            addCriterion("CD_KOSHINSHA_KAISHA is null");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaIsNotNull() {
            addCriterion("CD_KOSHINSHA_KAISHA is not null");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaEqualTo(String value) {
            addCriterion("CD_KOSHINSHA_KAISHA =", value, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaNotEqualTo(String value) {
            addCriterion("CD_KOSHINSHA_KAISHA <>", value, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaGreaterThan(String value) {
            addCriterion("CD_KOSHINSHA_KAISHA >", value, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaGreaterThanOrEqualTo(String value) {
            addCriterion("CD_KOSHINSHA_KAISHA >=", value, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaLessThan(String value) {
            addCriterion("CD_KOSHINSHA_KAISHA <", value, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaLessThanOrEqualTo(String value) {
            addCriterion("CD_KOSHINSHA_KAISHA <=", value, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaLike(String value) {
            addCriterion("CD_KOSHINSHA_KAISHA like", value, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaNotLike(String value) {
            addCriterion("CD_KOSHINSHA_KAISHA not like", value, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaIn(List<String> values) {
            addCriterion("CD_KOSHINSHA_KAISHA in", values, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaNotIn(List<String> values) {
            addCriterion("CD_KOSHINSHA_KAISHA not in", values, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaBetween(String value1, String value2) {
            addCriterion("CD_KOSHINSHA_KAISHA between", value1, value2, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKoshinshaKaishaNotBetween(String value1, String value2) {
            addCriterion("CD_KOSHINSHA_KAISHA not between", value1, value2, "cdKoshinshaKaisha");
            return (Criteria) this;
        }

        public Criteria andCdHozonIsNull() {
            addCriterion("CD_HOZON is null");
            return (Criteria) this;
        }

        public Criteria andCdHozonIsNotNull() {
            addCriterion("CD_HOZON is not null");
            return (Criteria) this;
        }

        public Criteria andCdHozonEqualTo(String value) {
            addCriterion("CD_HOZON =", value, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonNotEqualTo(String value) {
            addCriterion("CD_HOZON <>", value, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonGreaterThan(String value) {
            addCriterion("CD_HOZON >", value, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonGreaterThanOrEqualTo(String value) {
            addCriterion("CD_HOZON >=", value, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonLessThan(String value) {
            addCriterion("CD_HOZON <", value, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonLessThanOrEqualTo(String value) {
            addCriterion("CD_HOZON <=", value, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonLike(String value) {
            addCriterion("CD_HOZON like", value, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonNotLike(String value) {
            addCriterion("CD_HOZON not like", value, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonIn(List<String> values) {
            addCriterion("CD_HOZON in", values, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonNotIn(List<String> values) {
            addCriterion("CD_HOZON not in", values, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonBetween(String value1, String value2) {
            addCriterion("CD_HOZON between", value1, value2, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdHozonNotBetween(String value1, String value2) {
            addCriterion("CD_HOZON not between", value1, value2, "cdHozon");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiIsNull() {
            addCriterion("CD_JT_SHIJI is null");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiIsNotNull() {
            addCriterion("CD_JT_SHIJI is not null");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiEqualTo(String value) {
            addCriterion("CD_JT_SHIJI =", value, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiNotEqualTo(String value) {
            addCriterion("CD_JT_SHIJI <>", value, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiGreaterThan(String value) {
            addCriterion("CD_JT_SHIJI >", value, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiGreaterThanOrEqualTo(String value) {
            addCriterion("CD_JT_SHIJI >=", value, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiLessThan(String value) {
            addCriterion("CD_JT_SHIJI <", value, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiLessThanOrEqualTo(String value) {
            addCriterion("CD_JT_SHIJI <=", value, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiLike(String value) {
            addCriterion("CD_JT_SHIJI like", value, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiNotLike(String value) {
            addCriterion("CD_JT_SHIJI not like", value, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiIn(List<String> values) {
            addCriterion("CD_JT_SHIJI in", values, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiNotIn(List<String> values) {
            addCriterion("CD_JT_SHIJI not in", values, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiBetween(String value1, String value2) {
            addCriterion("CD_JT_SHIJI between", value1, value2, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdJtShijiNotBetween(String value1, String value2) {
            addCriterion("CD_JT_SHIJI not between", value1, value2, "cdJtShiji");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinIsNull() {
            addCriterion("CD_KS_JT_SHIN is null");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinIsNotNull() {
            addCriterion("CD_KS_JT_SHIN is not null");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinEqualTo(String value) {
            addCriterion("CD_KS_JT_SHIN =", value, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinNotEqualTo(String value) {
            addCriterion("CD_KS_JT_SHIN <>", value, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinGreaterThan(String value) {
            addCriterion("CD_KS_JT_SHIN >", value, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinGreaterThanOrEqualTo(String value) {
            addCriterion("CD_KS_JT_SHIN >=", value, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinLessThan(String value) {
            addCriterion("CD_KS_JT_SHIN <", value, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinLessThanOrEqualTo(String value) {
            addCriterion("CD_KS_JT_SHIN <=", value, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinLike(String value) {
            addCriterion("CD_KS_JT_SHIN like", value, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinNotLike(String value) {
            addCriterion("CD_KS_JT_SHIN not like", value, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinIn(List<String> values) {
            addCriterion("CD_KS_JT_SHIN in", values, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinNotIn(List<String> values) {
            addCriterion("CD_KS_JT_SHIN not in", values, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinBetween(String value1, String value2) {
            addCriterion("CD_KS_JT_SHIN between", value1, value2, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdKsJtShinNotBetween(String value1, String value2) {
            addCriterion("CD_KS_JT_SHIN not between", value1, value2, "cdKsJtShin");
            return (Criteria) this;
        }

        public Criteria andCdMlJunIsNull() {
            addCriterion("CD_ML_JUN is null");
            return (Criteria) this;
        }

        public Criteria andCdMlJunIsNotNull() {
            addCriterion("CD_ML_JUN is not null");
            return (Criteria) this;
        }

        public Criteria andCdMlJunEqualTo(String value) {
            addCriterion("CD_ML_JUN =", value, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunNotEqualTo(String value) {
            addCriterion("CD_ML_JUN <>", value, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunGreaterThan(String value) {
            addCriterion("CD_ML_JUN >", value, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ML_JUN >=", value, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunLessThan(String value) {
            addCriterion("CD_ML_JUN <", value, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunLessThanOrEqualTo(String value) {
            addCriterion("CD_ML_JUN <=", value, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunLike(String value) {
            addCriterion("CD_ML_JUN like", value, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunNotLike(String value) {
            addCriterion("CD_ML_JUN not like", value, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunIn(List<String> values) {
            addCriterion("CD_ML_JUN in", values, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunNotIn(List<String> values) {
            addCriterion("CD_ML_JUN not in", values, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunBetween(String value1, String value2) {
            addCriterion("CD_ML_JUN between", value1, value2, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlJunNotBetween(String value1, String value2) {
            addCriterion("CD_ML_JUN not between", value1, value2, "cdMlJun");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaIsNull() {
            addCriterion("CD_ML_KAISHA is null");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaIsNotNull() {
            addCriterion("CD_ML_KAISHA is not null");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaEqualTo(String value) {
            addCriterion("CD_ML_KAISHA =", value, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaNotEqualTo(String value) {
            addCriterion("CD_ML_KAISHA <>", value, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaGreaterThan(String value) {
            addCriterion("CD_ML_KAISHA >", value, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ML_KAISHA >=", value, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaLessThan(String value) {
            addCriterion("CD_ML_KAISHA <", value, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaLessThanOrEqualTo(String value) {
            addCriterion("CD_ML_KAISHA <=", value, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaLike(String value) {
            addCriterion("CD_ML_KAISHA like", value, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaNotLike(String value) {
            addCriterion("CD_ML_KAISHA not like", value, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaIn(List<String> values) {
            addCriterion("CD_ML_KAISHA in", values, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaNotIn(List<String> values) {
            addCriterion("CD_ML_KAISHA not in", values, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaBetween(String value1, String value2) {
            addCriterion("CD_ML_KAISHA between", value1, value2, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaNotBetween(String value1, String value2) {
            addCriterion("CD_ML_KAISHA not between", value1, value2, "cdMlKaisha");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcIsNull() {
            addCriterion("CD_ML_KAISHA_CC is null");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcIsNotNull() {
            addCriterion("CD_ML_KAISHA_CC is not null");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcEqualTo(String value) {
            addCriterion("CD_ML_KAISHA_CC =", value, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcNotEqualTo(String value) {
            addCriterion("CD_ML_KAISHA_CC <>", value, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcGreaterThan(String value) {
            addCriterion("CD_ML_KAISHA_CC >", value, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ML_KAISHA_CC >=", value, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcLessThan(String value) {
            addCriterion("CD_ML_KAISHA_CC <", value, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcLessThanOrEqualTo(String value) {
            addCriterion("CD_ML_KAISHA_CC <=", value, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcLike(String value) {
            addCriterion("CD_ML_KAISHA_CC like", value, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcNotLike(String value) {
            addCriterion("CD_ML_KAISHA_CC not like", value, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcIn(List<String> values) {
            addCriterion("CD_ML_KAISHA_CC in", values, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcNotIn(List<String> values) {
            addCriterion("CD_ML_KAISHA_CC not in", values, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcBetween(String value1, String value2) {
            addCriterion("CD_ML_KAISHA_CC between", value1, value2, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlKaishaCcNotBetween(String value1, String value2) {
            addCriterion("CD_ML_KAISHA_CC not between", value1, value2, "cdMlKaishaCc");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanIsNull() {
            addCriterion("CD_ML_HANDAN is null");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanIsNotNull() {
            addCriterion("CD_ML_HANDAN is not null");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanEqualTo(String value) {
            addCriterion("CD_ML_HANDAN =", value, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanNotEqualTo(String value) {
            addCriterion("CD_ML_HANDAN <>", value, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanGreaterThan(String value) {
            addCriterion("CD_ML_HANDAN >", value, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ML_HANDAN >=", value, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanLessThan(String value) {
            addCriterion("CD_ML_HANDAN <", value, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanLessThanOrEqualTo(String value) {
            addCriterion("CD_ML_HANDAN <=", value, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanLike(String value) {
            addCriterion("CD_ML_HANDAN like", value, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanNotLike(String value) {
            addCriterion("CD_ML_HANDAN not like", value, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanIn(List<String> values) {
            addCriterion("CD_ML_HANDAN in", values, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanNotIn(List<String> values) {
            addCriterion("CD_ML_HANDAN not in", values, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanBetween(String value1, String value2) {
            addCriterion("CD_ML_HANDAN between", value1, value2, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlHandanNotBetween(String value1, String value2) {
            addCriterion("CD_ML_HANDAN not between", value1, value2, "cdMlHandan");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunIsNull() {
            addCriterion("CD_ML_KIJUN is null");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunIsNotNull() {
            addCriterion("CD_ML_KIJUN is not null");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunEqualTo(String value) {
            addCriterion("CD_ML_KIJUN =", value, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunNotEqualTo(String value) {
            addCriterion("CD_ML_KIJUN <>", value, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunGreaterThan(String value) {
            addCriterion("CD_ML_KIJUN >", value, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ML_KIJUN >=", value, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunLessThan(String value) {
            addCriterion("CD_ML_KIJUN <", value, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunLessThanOrEqualTo(String value) {
            addCriterion("CD_ML_KIJUN <=", value, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunLike(String value) {
            addCriterion("CD_ML_KIJUN like", value, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunNotLike(String value) {
            addCriterion("CD_ML_KIJUN not like", value, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunIn(List<String> values) {
            addCriterion("CD_ML_KIJUN in", values, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunNotIn(List<String> values) {
            addCriterion("CD_ML_KIJUN not in", values, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunBetween(String value1, String value2) {
            addCriterion("CD_ML_KIJUN between", value1, value2, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andCdMlKijunNotBetween(String value1, String value2) {
            addCriterion("CD_ML_KIJUN not between", value1, value2, "cdMlKijun");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoIsNull() {
            addCriterion("DT_ML_BUNSHO is null");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoIsNotNull() {
            addCriterion("DT_ML_BUNSHO is not null");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoEqualTo(String value) {
            addCriterion("DT_ML_BUNSHO =", value, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoNotEqualTo(String value) {
            addCriterion("DT_ML_BUNSHO <>", value, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoGreaterThan(String value) {
            addCriterion("DT_ML_BUNSHO >", value, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoGreaterThanOrEqualTo(String value) {
            addCriterion("DT_ML_BUNSHO >=", value, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoLessThan(String value) {
            addCriterion("DT_ML_BUNSHO <", value, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoLessThanOrEqualTo(String value) {
            addCriterion("DT_ML_BUNSHO <=", value, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoLike(String value) {
            addCriterion("DT_ML_BUNSHO like", value, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoNotLike(String value) {
            addCriterion("DT_ML_BUNSHO not like", value, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoIn(List<String> values) {
            addCriterion("DT_ML_BUNSHO in", values, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoNotIn(List<String> values) {
            addCriterion("DT_ML_BUNSHO not in", values, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoBetween(String value1, String value2) {
            addCriterion("DT_ML_BUNSHO between", value1, value2, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andDtMlBunshoNotBetween(String value1, String value2) {
            addCriterion("DT_ML_BUNSHO not between", value1, value2, "dtMlBunsho");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNull() {
            addCriterion("CD_LU_KAISHA is null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNotNull() {
            addCriterion("CD_LU_KAISHA is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaEqualTo(String value) {
            addCriterion("CD_LU_KAISHA =", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotEqualTo(String value) {
            addCriterion("CD_LU_KAISHA <>", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThan(String value) {
            addCriterion("CD_LU_KAISHA >", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_KAISHA >=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThan(String value) {
            addCriterion("CD_LU_KAISHA <", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_KAISHA <=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLike(String value) {
            addCriterion("CD_LU_KAISHA like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotLike(String value) {
            addCriterion("CD_LU_KAISHA not like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIn(List<String> values) {
            addCriterion("CD_LU_KAISHA in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotIn(List<String> values) {
            addCriterion("CD_LU_KAISHA not in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaBetween(String value1, String value2) {
            addCriterion("CD_LU_KAISHA between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotBetween(String value1, String value2) {
            addCriterion("CD_LU_KAISHA not between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNull() {
            addCriterion("CD_LU_USER is null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNotNull() {
            addCriterion("CD_LU_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserEqualTo(String value) {
            addCriterion("CD_LU_USER =", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotEqualTo(String value) {
            addCriterion("CD_LU_USER <>", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThan(String value) {
            addCriterion("CD_LU_USER >", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER >=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThan(String value) {
            addCriterion("CD_LU_USER <", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER <=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLike(String value) {
            addCriterion("CD_LU_USER like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotLike(String value) {
            addCriterion("CD_LU_USER not like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIn(List<String> values) {
            addCriterion("CD_LU_USER in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotIn(List<String> values) {
            addCriterion("CD_LU_USER not in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserBetween(String value1, String value2) {
            addCriterion("CD_LU_USER between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotBetween(String value1, String value2) {
            addCriterion("CD_LU_USER not between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNull() {
            addCriterion("TM_LU is null");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNotNull() {
            addCriterion("TM_LU is not null");
            return (Criteria) this;
        }

        public Criteria andTmLuEqualTo(LocalDateTime value) {
            addCriterion("TM_LU =", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <>", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThan(LocalDateTime value) {
            addCriterion("TM_LU >", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU >=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThan(LocalDateTime value) {
            addCriterion("TM_LU <", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuIn(List<LocalDateTime> values) {
            addCriterion("TM_LU in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotIn(List<LocalDateTime> values) {
            addCriterion("TM_LU not in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU not between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectIsNull() {
            addCriterion("DT_ML_SUBJECT is null");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectIsNotNull() {
            addCriterion("DT_ML_SUBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectEqualTo(String value) {
            addCriterion("DT_ML_SUBJECT =", value, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectNotEqualTo(String value) {
            addCriterion("DT_ML_SUBJECT <>", value, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectGreaterThan(String value) {
            addCriterion("DT_ML_SUBJECT >", value, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("DT_ML_SUBJECT >=", value, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectLessThan(String value) {
            addCriterion("DT_ML_SUBJECT <", value, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectLessThanOrEqualTo(String value) {
            addCriterion("DT_ML_SUBJECT <=", value, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectLike(String value) {
            addCriterion("DT_ML_SUBJECT like", value, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectNotLike(String value) {
            addCriterion("DT_ML_SUBJECT not like", value, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectIn(List<String> values) {
            addCriterion("DT_ML_SUBJECT in", values, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectNotIn(List<String> values) {
            addCriterion("DT_ML_SUBJECT not in", values, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectBetween(String value1, String value2) {
            addCriterion("DT_ML_SUBJECT between", value1, value2, "dtMlSubject");
            return (Criteria) this;
        }

        public Criteria andDtMlSubjectNotBetween(String value1, String value2) {
            addCriterion("DT_ML_SUBJECT not between", value1, value2, "dtMlSubject");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_MAIL_KANRI
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}