package com.asg.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TM_ROLEPERMISSION
 */
@Data
public class TmRolepermission implements Serializable {
    /**
     * Database Column Remarks:
     *   ロールID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_ROLEPERMISSION.CD_ROLE
     *
     * @mbg.generated
     */
    private String cdRole;

    /**
     * Database Column Remarks:
     *   パーミッションID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_ROLEPERMISSION.CD_PERMISSION
     *
     * @mbg.generated
     */
    private String cdPermission;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_ROLEPERMISSION.CD_LU_USER
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_ROLEPERMISSION.TM_LU
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}