package com.asg.domain.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TmRolepermissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public TmRolepermissionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCdRoleIsNull() {
            addCriterion("CD_ROLE is null");
            return (Criteria) this;
        }

        public Criteria andCdRoleIsNotNull() {
            addCriterion("CD_ROLE is not null");
            return (Criteria) this;
        }

        public Criteria andCdRoleEqualTo(String value) {
            addCriterion("CD_ROLE =", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleNotEqualTo(String value) {
            addCriterion("CD_ROLE <>", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleGreaterThan(String value) {
            addCriterion("CD_ROLE >", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ROLE >=", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleLessThan(String value) {
            addCriterion("CD_ROLE <", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleLessThanOrEqualTo(String value) {
            addCriterion("CD_ROLE <=", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleLike(String value) {
            addCriterion("CD_ROLE like", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleNotLike(String value) {
            addCriterion("CD_ROLE not like", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleIn(List<String> values) {
            addCriterion("CD_ROLE in", values, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleNotIn(List<String> values) {
            addCriterion("CD_ROLE not in", values, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleBetween(String value1, String value2) {
            addCriterion("CD_ROLE between", value1, value2, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleNotBetween(String value1, String value2) {
            addCriterion("CD_ROLE not between", value1, value2, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdPermissionIsNull() {
            addCriterion("CD_PERMISSION is null");
            return (Criteria) this;
        }

        public Criteria andCdPermissionIsNotNull() {
            addCriterion("CD_PERMISSION is not null");
            return (Criteria) this;
        }

        public Criteria andCdPermissionEqualTo(String value) {
            addCriterion("CD_PERMISSION =", value, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionNotEqualTo(String value) {
            addCriterion("CD_PERMISSION <>", value, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionGreaterThan(String value) {
            addCriterion("CD_PERMISSION >", value, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionGreaterThanOrEqualTo(String value) {
            addCriterion("CD_PERMISSION >=", value, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionLessThan(String value) {
            addCriterion("CD_PERMISSION <", value, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionLessThanOrEqualTo(String value) {
            addCriterion("CD_PERMISSION <=", value, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionLike(String value) {
            addCriterion("CD_PERMISSION like", value, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionNotLike(String value) {
            addCriterion("CD_PERMISSION not like", value, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionIn(List<String> values) {
            addCriterion("CD_PERMISSION in", values, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionNotIn(List<String> values) {
            addCriterion("CD_PERMISSION not in", values, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionBetween(String value1, String value2) {
            addCriterion("CD_PERMISSION between", value1, value2, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdPermissionNotBetween(String value1, String value2) {
            addCriterion("CD_PERMISSION not between", value1, value2, "cdPermission");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNull() {
            addCriterion("CD_LU_USER is null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNotNull() {
            addCriterion("CD_LU_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserEqualTo(String value) {
            addCriterion("CD_LU_USER =", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotEqualTo(String value) {
            addCriterion("CD_LU_USER <>", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThan(String value) {
            addCriterion("CD_LU_USER >", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER >=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThan(String value) {
            addCriterion("CD_LU_USER <", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER <=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLike(String value) {
            addCriterion("CD_LU_USER like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotLike(String value) {
            addCriterion("CD_LU_USER not like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIn(List<String> values) {
            addCriterion("CD_LU_USER in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotIn(List<String> values) {
            addCriterion("CD_LU_USER not in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserBetween(String value1, String value2) {
            addCriterion("CD_LU_USER between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotBetween(String value1, String value2) {
            addCriterion("CD_LU_USER not between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNull() {
            addCriterion("TM_LU is null");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNotNull() {
            addCriterion("TM_LU is not null");
            return (Criteria) this;
        }

        public Criteria andTmLuEqualTo(LocalDateTime value) {
            addCriterion("TM_LU =", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <>", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThan(LocalDateTime value) {
            addCriterion("TM_LU >", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU >=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThan(LocalDateTime value) {
            addCriterion("TM_LU <", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuIn(List<LocalDateTime> values) {
            addCriterion("TM_LU in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotIn(List<LocalDateTime> values) {
            addCriterion("TM_LU not in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU not between", value1, value2, "tmLu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_ROLEPERMISSION
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}