package com.asg.domain.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TmUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public TmUserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCdUserIsNull() {
            addCriterion("CD_USER is null");
            return (Criteria) this;
        }

        public Criteria andCdUserIsNotNull() {
            addCriterion("CD_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCdUserEqualTo(Integer value) {
            addCriterion("CD_USER =", value, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserNotEqualTo(Integer value) {
            addCriterion("CD_USER <>", value, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserGreaterThan(Integer value) {
            addCriterion("CD_USER >", value, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("CD_USER >=", value, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserLessThan(Integer value) {
            addCriterion("CD_USER <", value, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserLessThanOrEqualTo(Integer value) {
            addCriterion("CD_USER <=", value, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserIn(List<Integer> values) {
            addCriterion("CD_USER in", values, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserNotIn(List<Integer> values) {
            addCriterion("CD_USER not in", values, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserBetween(Integer value1, Integer value2) {
            addCriterion("CD_USER between", value1, value2, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdUserNotBetween(Integer value1, Integer value2) {
            addCriterion("CD_USER not between", value1, value2, "cdUser");
            return (Criteria) this;
        }

        public Criteria andCdKaishaIsNull() {
            addCriterion("CD_KAISHA is null");
            return (Criteria) this;
        }

        public Criteria andCdKaishaIsNotNull() {
            addCriterion("CD_KAISHA is not null");
            return (Criteria) this;
        }

        public Criteria andCdKaishaEqualTo(String value) {
            addCriterion("CD_KAISHA =", value, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaNotEqualTo(String value) {
            addCriterion("CD_KAISHA <>", value, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaGreaterThan(String value) {
            addCriterion("CD_KAISHA >", value, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaGreaterThanOrEqualTo(String value) {
            addCriterion("CD_KAISHA >=", value, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaLessThan(String value) {
            addCriterion("CD_KAISHA <", value, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaLessThanOrEqualTo(String value) {
            addCriterion("CD_KAISHA <=", value, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaLike(String value) {
            addCriterion("CD_KAISHA like", value, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaNotLike(String value) {
            addCriterion("CD_KAISHA not like", value, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaIn(List<String> values) {
            addCriterion("CD_KAISHA in", values, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaNotIn(List<String> values) {
            addCriterion("CD_KAISHA not in", values, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaBetween(String value1, String value2) {
            addCriterion("CD_KAISHA between", value1, value2, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdKaishaNotBetween(String value1, String value2) {
            addCriterion("CD_KAISHA not between", value1, value2, "cdKaisha");
            return (Criteria) this;
        }

        public Criteria andCdUserOldIsNull() {
            addCriterion("CD_USER_OLD is null");
            return (Criteria) this;
        }

        public Criteria andCdUserOldIsNotNull() {
            addCriterion("CD_USER_OLD is not null");
            return (Criteria) this;
        }

        public Criteria andCdUserOldEqualTo(String value) {
            addCriterion("CD_USER_OLD =", value, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldNotEqualTo(String value) {
            addCriterion("CD_USER_OLD <>", value, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldGreaterThan(String value) {
            addCriterion("CD_USER_OLD >", value, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldGreaterThanOrEqualTo(String value) {
            addCriterion("CD_USER_OLD >=", value, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldLessThan(String value) {
            addCriterion("CD_USER_OLD <", value, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldLessThanOrEqualTo(String value) {
            addCriterion("CD_USER_OLD <=", value, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldLike(String value) {
            addCriterion("CD_USER_OLD like", value, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldNotLike(String value) {
            addCriterion("CD_USER_OLD not like", value, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldIn(List<String> values) {
            addCriterion("CD_USER_OLD in", values, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldNotIn(List<String> values) {
            addCriterion("CD_USER_OLD not in", values, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldBetween(String value1, String value2) {
            addCriterion("CD_USER_OLD between", value1, value2, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andCdUserOldNotBetween(String value1, String value2) {
            addCriterion("CD_USER_OLD not between", value1, value2, "cdUserOld");
            return (Criteria) this;
        }

        public Criteria andKjUserIsNull() {
            addCriterion("KJ_USER is null");
            return (Criteria) this;
        }

        public Criteria andKjUserIsNotNull() {
            addCriterion("KJ_USER is not null");
            return (Criteria) this;
        }

        public Criteria andKjUserEqualTo(String value) {
            addCriterion("KJ_USER =", value, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserNotEqualTo(String value) {
            addCriterion("KJ_USER <>", value, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserGreaterThan(String value) {
            addCriterion("KJ_USER >", value, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserGreaterThanOrEqualTo(String value) {
            addCriterion("KJ_USER >=", value, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserLessThan(String value) {
            addCriterion("KJ_USER <", value, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserLessThanOrEqualTo(String value) {
            addCriterion("KJ_USER <=", value, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserLike(String value) {
            addCriterion("KJ_USER like", value, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserNotLike(String value) {
            addCriterion("KJ_USER not like", value, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserIn(List<String> values) {
            addCriterion("KJ_USER in", values, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserNotIn(List<String> values) {
            addCriterion("KJ_USER not in", values, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserBetween(String value1, String value2) {
            addCriterion("KJ_USER between", value1, value2, "kjUser");
            return (Criteria) this;
        }

        public Criteria andKjUserNotBetween(String value1, String value2) {
            addCriterion("KJ_USER not between", value1, value2, "kjUser");
            return (Criteria) this;
        }

        public Criteria andDtPasswordIsNull() {
            addCriterion("DT_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andDtPasswordIsNotNull() {
            addCriterion("DT_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andDtPasswordEqualTo(String value) {
            addCriterion("DT_PASSWORD =", value, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordNotEqualTo(String value) {
            addCriterion("DT_PASSWORD <>", value, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordGreaterThan(String value) {
            addCriterion("DT_PASSWORD >", value, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("DT_PASSWORD >=", value, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordLessThan(String value) {
            addCriterion("DT_PASSWORD <", value, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordLessThanOrEqualTo(String value) {
            addCriterion("DT_PASSWORD <=", value, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordLike(String value) {
            addCriterion("DT_PASSWORD like", value, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordNotLike(String value) {
            addCriterion("DT_PASSWORD not like", value, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordIn(List<String> values) {
            addCriterion("DT_PASSWORD in", values, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordNotIn(List<String> values) {
            addCriterion("DT_PASSWORD not in", values, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordBetween(String value1, String value2) {
            addCriterion("DT_PASSWORD between", value1, value2, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtPasswordNotBetween(String value1, String value2) {
            addCriterion("DT_PASSWORD not between", value1, value2, "dtPassword");
            return (Criteria) this;
        }

        public Criteria andDtMailIsNull() {
            addCriterion("DT_MAIL is null");
            return (Criteria) this;
        }

        public Criteria andDtMailIsNotNull() {
            addCriterion("DT_MAIL is not null");
            return (Criteria) this;
        }

        public Criteria andDtMailEqualTo(String value) {
            addCriterion("DT_MAIL =", value, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailNotEqualTo(String value) {
            addCriterion("DT_MAIL <>", value, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailGreaterThan(String value) {
            addCriterion("DT_MAIL >", value, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailGreaterThanOrEqualTo(String value) {
            addCriterion("DT_MAIL >=", value, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailLessThan(String value) {
            addCriterion("DT_MAIL <", value, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailLessThanOrEqualTo(String value) {
            addCriterion("DT_MAIL <=", value, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailLike(String value) {
            addCriterion("DT_MAIL like", value, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailNotLike(String value) {
            addCriterion("DT_MAIL not like", value, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailIn(List<String> values) {
            addCriterion("DT_MAIL in", values, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailNotIn(List<String> values) {
            addCriterion("DT_MAIL not in", values, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailBetween(String value1, String value2) {
            addCriterion("DT_MAIL between", value1, value2, "dtMail");
            return (Criteria) this;
        }

        public Criteria andDtMailNotBetween(String value1, String value2) {
            addCriterion("DT_MAIL not between", value1, value2, "dtMail");
            return (Criteria) this;
        }

        public Criteria andKjBushoIsNull() {
            addCriterion("KJ_BUSHO is null");
            return (Criteria) this;
        }

        public Criteria andKjBushoIsNotNull() {
            addCriterion("KJ_BUSHO is not null");
            return (Criteria) this;
        }

        public Criteria andKjBushoEqualTo(String value) {
            addCriterion("KJ_BUSHO =", value, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoNotEqualTo(String value) {
            addCriterion("KJ_BUSHO <>", value, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoGreaterThan(String value) {
            addCriterion("KJ_BUSHO >", value, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoGreaterThanOrEqualTo(String value) {
            addCriterion("KJ_BUSHO >=", value, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoLessThan(String value) {
            addCriterion("KJ_BUSHO <", value, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoLessThanOrEqualTo(String value) {
            addCriterion("KJ_BUSHO <=", value, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoLike(String value) {
            addCriterion("KJ_BUSHO like", value, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoNotLike(String value) {
            addCriterion("KJ_BUSHO not like", value, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoIn(List<String> values) {
            addCriterion("KJ_BUSHO in", values, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoNotIn(List<String> values) {
            addCriterion("KJ_BUSHO not in", values, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoBetween(String value1, String value2) {
            addCriterion("KJ_BUSHO between", value1, value2, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andKjBushoNotBetween(String value1, String value2) {
            addCriterion("KJ_BUSHO not between", value1, value2, "kjBusho");
            return (Criteria) this;
        }

        public Criteria andDtTelIsNull() {
            addCriterion("DT_TEL is null");
            return (Criteria) this;
        }

        public Criteria andDtTelIsNotNull() {
            addCriterion("DT_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andDtTelEqualTo(String value) {
            addCriterion("DT_TEL =", value, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelNotEqualTo(String value) {
            addCriterion("DT_TEL <>", value, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelGreaterThan(String value) {
            addCriterion("DT_TEL >", value, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelGreaterThanOrEqualTo(String value) {
            addCriterion("DT_TEL >=", value, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelLessThan(String value) {
            addCriterion("DT_TEL <", value, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelLessThanOrEqualTo(String value) {
            addCriterion("DT_TEL <=", value, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelLike(String value) {
            addCriterion("DT_TEL like", value, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelNotLike(String value) {
            addCriterion("DT_TEL not like", value, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelIn(List<String> values) {
            addCriterion("DT_TEL in", values, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelNotIn(List<String> values) {
            addCriterion("DT_TEL not in", values, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelBetween(String value1, String value2) {
            addCriterion("DT_TEL between", value1, value2, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtTelNotBetween(String value1, String value2) {
            addCriterion("DT_TEL not between", value1, value2, "dtTel");
            return (Criteria) this;
        }

        public Criteria andDtFaxIsNull() {
            addCriterion("DT_FAX is null");
            return (Criteria) this;
        }

        public Criteria andDtFaxIsNotNull() {
            addCriterion("DT_FAX is not null");
            return (Criteria) this;
        }

        public Criteria andDtFaxEqualTo(String value) {
            addCriterion("DT_FAX =", value, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxNotEqualTo(String value) {
            addCriterion("DT_FAX <>", value, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxGreaterThan(String value) {
            addCriterion("DT_FAX >", value, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxGreaterThanOrEqualTo(String value) {
            addCriterion("DT_FAX >=", value, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxLessThan(String value) {
            addCriterion("DT_FAX <", value, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxLessThanOrEqualTo(String value) {
            addCriterion("DT_FAX <=", value, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxLike(String value) {
            addCriterion("DT_FAX like", value, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxNotLike(String value) {
            addCriterion("DT_FAX not like", value, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxIn(List<String> values) {
            addCriterion("DT_FAX in", values, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxNotIn(List<String> values) {
            addCriterion("DT_FAX not in", values, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxBetween(String value1, String value2) {
            addCriterion("DT_FAX between", value1, value2, "dtFax");
            return (Criteria) this;
        }

        public Criteria andDtFaxNotBetween(String value1, String value2) {
            addCriterion("DT_FAX not between", value1, value2, "dtFax");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiIsNull() {
            addCriterion("CD_SHIYOKAHI is null");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiIsNotNull() {
            addCriterion("CD_SHIYOKAHI is not null");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiEqualTo(String value) {
            addCriterion("CD_SHIYOKAHI =", value, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiNotEqualTo(String value) {
            addCriterion("CD_SHIYOKAHI <>", value, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiGreaterThan(String value) {
            addCriterion("CD_SHIYOKAHI >", value, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiGreaterThanOrEqualTo(String value) {
            addCriterion("CD_SHIYOKAHI >=", value, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiLessThan(String value) {
            addCriterion("CD_SHIYOKAHI <", value, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiLessThanOrEqualTo(String value) {
            addCriterion("CD_SHIYOKAHI <=", value, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiLike(String value) {
            addCriterion("CD_SHIYOKAHI like", value, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiNotLike(String value) {
            addCriterion("CD_SHIYOKAHI not like", value, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiIn(List<String> values) {
            addCriterion("CD_SHIYOKAHI in", values, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiNotIn(List<String> values) {
            addCriterion("CD_SHIYOKAHI not in", values, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiBetween(String value1, String value2) {
            addCriterion("CD_SHIYOKAHI between", value1, value2, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdShiyokahiNotBetween(String value1, String value2) {
            addCriterion("CD_SHIYOKAHI not between", value1, value2, "cdShiyokahi");
            return (Criteria) this;
        }

        public Criteria andCdRoleIsNull() {
            addCriterion("CD_ROLE is null");
            return (Criteria) this;
        }

        public Criteria andCdRoleIsNotNull() {
            addCriterion("CD_ROLE is not null");
            return (Criteria) this;
        }

        public Criteria andCdRoleEqualTo(String value) {
            addCriterion("CD_ROLE =", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleNotEqualTo(String value) {
            addCriterion("CD_ROLE <>", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleGreaterThan(String value) {
            addCriterion("CD_ROLE >", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ROLE >=", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleLessThan(String value) {
            addCriterion("CD_ROLE <", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleLessThanOrEqualTo(String value) {
            addCriterion("CD_ROLE <=", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleLike(String value) {
            addCriterion("CD_ROLE like", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleNotLike(String value) {
            addCriterion("CD_ROLE not like", value, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleIn(List<String> values) {
            addCriterion("CD_ROLE in", values, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleNotIn(List<String> values) {
            addCriterion("CD_ROLE not in", values, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleBetween(String value1, String value2) {
            addCriterion("CD_ROLE between", value1, value2, "cdRole");
            return (Criteria) this;
        }

        public Criteria andCdRoleNotBetween(String value1, String value2) {
            addCriterion("CD_ROLE not between", value1, value2, "cdRole");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyIsNull() {
            addCriterion("DT_STARTKEY is null");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyIsNotNull() {
            addCriterion("DT_STARTKEY is not null");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyEqualTo(String value) {
            addCriterion("DT_STARTKEY =", value, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyNotEqualTo(String value) {
            addCriterion("DT_STARTKEY <>", value, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyGreaterThan(String value) {
            addCriterion("DT_STARTKEY >", value, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyGreaterThanOrEqualTo(String value) {
            addCriterion("DT_STARTKEY >=", value, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyLessThan(String value) {
            addCriterion("DT_STARTKEY <", value, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyLessThanOrEqualTo(String value) {
            addCriterion("DT_STARTKEY <=", value, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyLike(String value) {
            addCriterion("DT_STARTKEY like", value, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyNotLike(String value) {
            addCriterion("DT_STARTKEY not like", value, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyIn(List<String> values) {
            addCriterion("DT_STARTKEY in", values, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyNotIn(List<String> values) {
            addCriterion("DT_STARTKEY not in", values, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyBetween(String value1, String value2) {
            addCriterion("DT_STARTKEY between", value1, value2, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andDtStartkeyNotBetween(String value1, String value2) {
            addCriterion("DT_STARTKEY not between", value1, value2, "dtStartkey");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNull() {
            addCriterion("CD_LU_KAISHA is null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIsNotNull() {
            addCriterion("CD_LU_KAISHA is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaEqualTo(String value) {
            addCriterion("CD_LU_KAISHA =", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotEqualTo(String value) {
            addCriterion("CD_LU_KAISHA <>", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThan(String value) {
            addCriterion("CD_LU_KAISHA >", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_KAISHA >=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThan(String value) {
            addCriterion("CD_LU_KAISHA <", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_KAISHA <=", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaLike(String value) {
            addCriterion("CD_LU_KAISHA like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotLike(String value) {
            addCriterion("CD_LU_KAISHA not like", value, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaIn(List<String> values) {
            addCriterion("CD_LU_KAISHA in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotIn(List<String> values) {
            addCriterion("CD_LU_KAISHA not in", values, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaBetween(String value1, String value2) {
            addCriterion("CD_LU_KAISHA between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuKaishaNotBetween(String value1, String value2) {
            addCriterion("CD_LU_KAISHA not between", value1, value2, "cdLuKaisha");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNull() {
            addCriterion("CD_LU_USER is null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNotNull() {
            addCriterion("CD_LU_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserEqualTo(String value) {
            addCriterion("CD_LU_USER =", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotEqualTo(String value) {
            addCriterion("CD_LU_USER <>", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThan(String value) {
            addCriterion("CD_LU_USER >", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER >=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThan(String value) {
            addCriterion("CD_LU_USER <", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER <=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLike(String value) {
            addCriterion("CD_LU_USER like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotLike(String value) {
            addCriterion("CD_LU_USER not like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIn(List<String> values) {
            addCriterion("CD_LU_USER in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotIn(List<String> values) {
            addCriterion("CD_LU_USER not in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserBetween(String value1, String value2) {
            addCriterion("CD_LU_USER between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotBetween(String value1, String value2) {
            addCriterion("CD_LU_USER not between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNull() {
            addCriterion("TM_LU is null");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNotNull() {
            addCriterion("TM_LU is not null");
            return (Criteria) this;
        }

        public Criteria andTmLuEqualTo(LocalDateTime value) {
            addCriterion("TM_LU =", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <>", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThan(LocalDateTime value) {
            addCriterion("TM_LU >", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU >=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThan(LocalDateTime value) {
            addCriterion("TM_LU <", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuIn(List<LocalDateTime> values) {
            addCriterion("TM_LU in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotIn(List<LocalDateTime> values) {
            addCriterion("TM_LU not in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU not between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginIsNull() {
            addCriterion("TM_LAST_LOGIN is null");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginIsNotNull() {
            addCriterion("TM_LAST_LOGIN is not null");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginEqualTo(LocalDateTime value) {
            addCriterion("TM_LAST_LOGIN =", value, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginNotEqualTo(LocalDateTime value) {
            addCriterion("TM_LAST_LOGIN <>", value, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginGreaterThan(LocalDateTime value) {
            addCriterion("TM_LAST_LOGIN >", value, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LAST_LOGIN >=", value, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginLessThan(LocalDateTime value) {
            addCriterion("TM_LAST_LOGIN <", value, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LAST_LOGIN <=", value, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginIn(List<LocalDateTime> values) {
            addCriterion("TM_LAST_LOGIN in", values, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginNotIn(List<LocalDateTime> values) {
            addCriterion("TM_LAST_LOGIN not in", values, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LAST_LOGIN between", value1, value2, "tmLastLogin");
            return (Criteria) this;
        }

        public Criteria andTmLastLoginNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LAST_LOGIN not between", value1, value2, "tmLastLogin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_USER
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}