package com.asg.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TM_USER
 */
@Data
public class TmUser implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザーID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.CD_USER
     *
     * @mbg.generated
     */
    private Integer cdUser;

    /**
     * Database Column Remarks:
     *   会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.CD_KAISHA
     *
     * @mbg.generated
     */
    private String cdKaisha;

    /**
     * Database Column Remarks:
     *   旧ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.CD_USER_OLD
     *
     * @mbg.generated
     */
    private String cdUserOld;

    /**
     * Database Column Remarks:
     *   ユーザ名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.KJ_USER
     *
     * @mbg.generated
     */
    private String kjUser;

    /**
     * Database Column Remarks:
     *   パスワード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.DT_PASSWORD
     *
     * @mbg.generated
     */
    private String dtPassword;

    /**
     * Database Column Remarks:
     *   メールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.DT_MAIL
     *
     * @mbg.generated
     */
    private String dtMail;

    /**
     * Database Column Remarks:
     *   部署名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.KJ_BUSHO
     *
     * @mbg.generated
     */
    private String kjBusho;

    /**
     * Database Column Remarks:
     *   電話番号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.DT_TEL
     *
     * @mbg.generated
     */
    private String dtTel;

    /**
     * Database Column Remarks:
     *   FAX番号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.DT_FAX
     *
     * @mbg.generated
     */
    private String dtFax;

    /**
     * Database Column Remarks:
     *   使用可否区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.CD_SHIYOKAHI
     *
     * @mbg.generated
     */
    private String cdShiyokahi;

    /**
     * Database Column Remarks:
     *   ロール
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.CD_ROLE
     *
     * @mbg.generated
     */
    private String cdRole;

    /**
     * Database Column Remarks:
     *   使用開始キー
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.DT_STARTKEY
     *
     * @mbg.generated
     */
    private String dtStartkey;

    /**
     * Database Column Remarks:
     *   最終更新会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.CD_LU_KAISHA
     *
     * @mbg.generated
     */
    private String cdLuKaisha;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.CD_LU_USER
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.TM_LU
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * Database Column Remarks:
     *   最終ログイン日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM_USER.TM_LAST_LOGIN
     *
     * @mbg.generated
     */
    private LocalDateTime tmLastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TM_USER
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}