package com.asg.domain.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TtJohoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public TtJohoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCdSeqIsNull() {
            addCriterion("CD_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andCdSeqIsNotNull() {
            addCriterion("CD_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andCdSeqEqualTo(Long value) {
            addCriterion("CD_SEQ =", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqNotEqualTo(Long value) {
            addCriterion("CD_SEQ <>", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqGreaterThan(Long value) {
            addCriterion("CD_SEQ >", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("CD_SEQ >=", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqLessThan(Long value) {
            addCriterion("CD_SEQ <", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqLessThanOrEqualTo(Long value) {
            addCriterion("CD_SEQ <=", value, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqIn(List<Long> values) {
            addCriterion("CD_SEQ in", values, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqNotIn(List<Long> values) {
            addCriterion("CD_SEQ not in", values, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqBetween(Long value1, Long value2) {
            addCriterion("CD_SEQ between", value1, value2, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdSeqNotBetween(Long value1, Long value2) {
            addCriterion("CD_SEQ not between", value1, value2, "cdSeq");
            return (Criteria) this;
        }

        public Criteria andCdBrowseIsNull() {
            addCriterion("CD_BROWSE is null");
            return (Criteria) this;
        }

        public Criteria andCdBrowseIsNotNull() {
            addCriterion("CD_BROWSE is not null");
            return (Criteria) this;
        }

        public Criteria andCdBrowseEqualTo(String value) {
            addCriterion("CD_BROWSE =", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseNotEqualTo(String value) {
            addCriterion("CD_BROWSE <>", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseGreaterThan(String value) {
            addCriterion("CD_BROWSE >", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseGreaterThanOrEqualTo(String value) {
            addCriterion("CD_BROWSE >=", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseLessThan(String value) {
            addCriterion("CD_BROWSE <", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseLessThanOrEqualTo(String value) {
            addCriterion("CD_BROWSE <=", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseLike(String value) {
            addCriterion("CD_BROWSE like", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseNotLike(String value) {
            addCriterion("CD_BROWSE not like", value, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseIn(List<String> values) {
            addCriterion("CD_BROWSE in", values, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseNotIn(List<String> values) {
            addCriterion("CD_BROWSE not in", values, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseBetween(String value1, String value2) {
            addCriterion("CD_BROWSE between", value1, value2, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdBrowseNotBetween(String value1, String value2) {
            addCriterion("CD_BROWSE not between", value1, value2, "cdBrowse");
            return (Criteria) this;
        }

        public Criteria andCdCategoryIsNull() {
            addCriterion("CD_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andCdCategoryIsNotNull() {
            addCriterion("CD_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andCdCategoryEqualTo(String value) {
            addCriterion("CD_CATEGORY =", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryNotEqualTo(String value) {
            addCriterion("CD_CATEGORY <>", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryGreaterThan(String value) {
            addCriterion("CD_CATEGORY >", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("CD_CATEGORY >=", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryLessThan(String value) {
            addCriterion("CD_CATEGORY <", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryLessThanOrEqualTo(String value) {
            addCriterion("CD_CATEGORY <=", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryLike(String value) {
            addCriterion("CD_CATEGORY like", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryNotLike(String value) {
            addCriterion("CD_CATEGORY not like", value, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryIn(List<String> values) {
            addCriterion("CD_CATEGORY in", values, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryNotIn(List<String> values) {
            addCriterion("CD_CATEGORY not in", values, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryBetween(String value1, String value2) {
            addCriterion("CD_CATEGORY between", value1, value2, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andCdCategoryNotBetween(String value1, String value2) {
            addCriterion("CD_CATEGORY not between", value1, value2, "cdCategory");
            return (Criteria) this;
        }

        public Criteria andTmReleaseIsNull() {
            addCriterion("TM_RELEASE is null");
            return (Criteria) this;
        }

        public Criteria andTmReleaseIsNotNull() {
            addCriterion("TM_RELEASE is not null");
            return (Criteria) this;
        }

        public Criteria andTmReleaseEqualTo(LocalDateTime value) {
            addCriterion("TM_RELEASE =", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseNotEqualTo(LocalDateTime value) {
            addCriterion("TM_RELEASE <>", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseGreaterThan(LocalDateTime value) {
            addCriterion("TM_RELEASE >", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_RELEASE >=", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseLessThan(LocalDateTime value) {
            addCriterion("TM_RELEASE <", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_RELEASE <=", value, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseIn(List<LocalDateTime> values) {
            addCriterion("TM_RELEASE in", values, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseNotIn(List<LocalDateTime> values) {
            addCriterion("TM_RELEASE not in", values, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_RELEASE between", value1, value2, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andTmReleaseNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_RELEASE not between", value1, value2, "tmRelease");
            return (Criteria) this;
        }

        public Criteria andKjTitleIsNull() {
            addCriterion("KJ_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andKjTitleIsNotNull() {
            addCriterion("KJ_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andKjTitleEqualTo(String value) {
            addCriterion("KJ_TITLE =", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleNotEqualTo(String value) {
            addCriterion("KJ_TITLE <>", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleGreaterThan(String value) {
            addCriterion("KJ_TITLE >", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleGreaterThanOrEqualTo(String value) {
            addCriterion("KJ_TITLE >=", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleLessThan(String value) {
            addCriterion("KJ_TITLE <", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleLessThanOrEqualTo(String value) {
            addCriterion("KJ_TITLE <=", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleLike(String value) {
            addCriterion("KJ_TITLE like", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleNotLike(String value) {
            addCriterion("KJ_TITLE not like", value, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleIn(List<String> values) {
            addCriterion("KJ_TITLE in", values, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleNotIn(List<String> values) {
            addCriterion("KJ_TITLE not in", values, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleBetween(String value1, String value2) {
            addCriterion("KJ_TITLE between", value1, value2, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andKjTitleNotBetween(String value1, String value2) {
            addCriterion("KJ_TITLE not between", value1, value2, "kjTitle");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseIsNull() {
            addCriterion("DT_OSHIRASE is null");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseIsNotNull() {
            addCriterion("DT_OSHIRASE is not null");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseEqualTo(String value) {
            addCriterion("DT_OSHIRASE =", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseNotEqualTo(String value) {
            addCriterion("DT_OSHIRASE <>", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseGreaterThan(String value) {
            addCriterion("DT_OSHIRASE >", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseGreaterThanOrEqualTo(String value) {
            addCriterion("DT_OSHIRASE >=", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseLessThan(String value) {
            addCriterion("DT_OSHIRASE <", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseLessThanOrEqualTo(String value) {
            addCriterion("DT_OSHIRASE <=", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseLike(String value) {
            addCriterion("DT_OSHIRASE like", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseNotLike(String value) {
            addCriterion("DT_OSHIRASE not like", value, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseIn(List<String> values) {
            addCriterion("DT_OSHIRASE in", values, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseNotIn(List<String> values) {
            addCriterion("DT_OSHIRASE not in", values, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseBetween(String value1, String value2) {
            addCriterion("DT_OSHIRASE between", value1, value2, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andDtOshiraseNotBetween(String value1, String value2) {
            addCriterion("DT_OSHIRASE not between", value1, value2, "dtOshirase");
            return (Criteria) this;
        }

        public Criteria andTmLimitIsNull() {
            addCriterion("TM_LIMIT is null");
            return (Criteria) this;
        }

        public Criteria andTmLimitIsNotNull() {
            addCriterion("TM_LIMIT is not null");
            return (Criteria) this;
        }

        public Criteria andTmLimitEqualTo(LocalDateTime value) {
            addCriterion("TM_LIMIT =", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitNotEqualTo(LocalDateTime value) {
            addCriterion("TM_LIMIT <>", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitGreaterThan(LocalDateTime value) {
            addCriterion("TM_LIMIT >", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LIMIT >=", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitLessThan(LocalDateTime value) {
            addCriterion("TM_LIMIT <", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LIMIT <=", value, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitIn(List<LocalDateTime> values) {
            addCriterion("TM_LIMIT in", values, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitNotIn(List<LocalDateTime> values) {
            addCriterion("TM_LIMIT not in", values, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LIMIT between", value1, value2, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andTmLimitNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LIMIT not between", value1, value2, "tmLimit");
            return (Criteria) this;
        }

        public Criteria andDtFileIsNull() {
            addCriterion("DT_FILE is null");
            return (Criteria) this;
        }

        public Criteria andDtFileIsNotNull() {
            addCriterion("DT_FILE is not null");
            return (Criteria) this;
        }

        public Criteria andDtFileEqualTo(String value) {
            addCriterion("DT_FILE =", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileNotEqualTo(String value) {
            addCriterion("DT_FILE <>", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileGreaterThan(String value) {
            addCriterion("DT_FILE >", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileGreaterThanOrEqualTo(String value) {
            addCriterion("DT_FILE >=", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileLessThan(String value) {
            addCriterion("DT_FILE <", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileLessThanOrEqualTo(String value) {
            addCriterion("DT_FILE <=", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileLike(String value) {
            addCriterion("DT_FILE like", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileNotLike(String value) {
            addCriterion("DT_FILE not like", value, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileIn(List<String> values) {
            addCriterion("DT_FILE in", values, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileNotIn(List<String> values) {
            addCriterion("DT_FILE not in", values, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileBetween(String value1, String value2) {
            addCriterion("DT_FILE between", value1, value2, "dtFile");
            return (Criteria) this;
        }

        public Criteria andDtFileNotBetween(String value1, String value2) {
            addCriterion("DT_FILE not between", value1, value2, "dtFile");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNull() {
            addCriterion("CD_LU_USER is null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIsNotNull() {
            addCriterion("CD_LU_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCdLuUserEqualTo(String value) {
            addCriterion("CD_LU_USER =", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotEqualTo(String value) {
            addCriterion("CD_LU_USER <>", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThan(String value) {
            addCriterion("CD_LU_USER >", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserGreaterThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER >=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThan(String value) {
            addCriterion("CD_LU_USER <", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLessThanOrEqualTo(String value) {
            addCriterion("CD_LU_USER <=", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserLike(String value) {
            addCriterion("CD_LU_USER like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotLike(String value) {
            addCriterion("CD_LU_USER not like", value, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserIn(List<String> values) {
            addCriterion("CD_LU_USER in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotIn(List<String> values) {
            addCriterion("CD_LU_USER not in", values, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserBetween(String value1, String value2) {
            addCriterion("CD_LU_USER between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andCdLuUserNotBetween(String value1, String value2) {
            addCriterion("CD_LU_USER not between", value1, value2, "cdLuUser");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNull() {
            addCriterion("TM_LU is null");
            return (Criteria) this;
        }

        public Criteria andTmLuIsNotNull() {
            addCriterion("TM_LU is not null");
            return (Criteria) this;
        }

        public Criteria andTmLuEqualTo(LocalDateTime value) {
            addCriterion("TM_LU =", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <>", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThan(LocalDateTime value) {
            addCriterion("TM_LU >", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU >=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThan(LocalDateTime value) {
            addCriterion("TM_LU <", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("TM_LU <=", value, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuIn(List<LocalDateTime> values) {
            addCriterion("TM_LU in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotIn(List<LocalDateTime> values) {
            addCriterion("TM_LU not in", values, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU between", value1, value2, "tmLu");
            return (Criteria) this;
        }

        public Criteria andTmLuNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("TM_LU not between", value1, value2, "tmLu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_JOHO
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}