package com.asg.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TT_JOHO
 */
@Data
public class TtJoho implements Serializable {
    /**
     * Database Column Remarks:
     *   連番
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.CD_SEQ
     *
     * @mbg.generated
     */
    private Long cdSeq;

    /**
     * Database Column Remarks:
     *   閲覧可能範囲
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.CD_BROWSE
     *
     * @mbg.generated
     */
    private String cdBrowse;

    /**
     * Database Column Remarks:
     *   カテゴリ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.CD_CATEGORY
     *
     * @mbg.generated
     */
    private String cdCategory;

    /**
     * Database Column Remarks:
     *   公開日付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.TM_RELEASE
     *
     * @mbg.generated
     */
    private LocalDateTime tmRelease;

    /**
     * Database Column Remarks:
     *   タイトル
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.KJ_TITLE
     *
     * @mbg.generated
     */
    private String kjTitle;

    /**
     * Database Column Remarks:
     *   お知らせメッセージ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.DT_OSHIRASE
     *
     * @mbg.generated
     */
    private String dtOshirase;

    /**
     * Database Column Remarks:
     *   公開期限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.TM_LIMIT
     *
     * @mbg.generated
     */
    private LocalDateTime tmLimit;

    /**
     * Database Column Remarks:
     *   添付ファイル
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.DT_FILE
     *
     * @mbg.generated
     */
    private String dtFile;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.CD_LU_USER
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_JOHO.TM_LU
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_JOHO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}