package com.asg.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TT_KENMEI
 */
@Data
public class TtKenmei implements Serializable {
    /**
     * Database Column Remarks:
     *   内部件名ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_KENMEI
     *
     * @mbg.generated
     */
    private String cdKenmei;

    /**
     * Database Column Remarks:
     *   机上調査依頼日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.YMD_KIJOIRAI
     *
     * @mbg.generated
     */
    private LocalDateTime ymdKijoirai;

    /**
     * Database Column Remarks:
     *   机上調査回答期限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.YMD_KIJOKIGEN
     *
     * @mbg.generated
     */
    private LocalDateTime ymdKijokigen;

    /**
     * Database Column Remarks:
     *   机上調査最終回答日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.YMD_KIJOSAISHUKAITO
     *
     * @mbg.generated
     */
    private LocalDateTime ymdKijosaishukaito;

    /**
     * Database Column Remarks:
     *   現地調査依頼日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.YMD_GENCHIIRAI
     *
     * @mbg.generated
     */
    private LocalDateTime ymdGenchiirai;

    /**
     * Database Column Remarks:
     *   工事日程報告依頼日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.YMD_NITTEIIRAI
     *
     * @mbg.generated
     */
    private LocalDateTime ymdNitteiirai;

    /**
     * Database Column Remarks:
     *   初期担当ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_SHOKITANTOUSER
     *
     * @mbg.generated
     */
    private String cdShokitantouser;

    /**
     * Database Column Remarks:
     *   現担当ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_GENTANTOUSER
     *
     * @mbg.generated
     */
    private String cdGentantouser;

    /**
     * Database Column Remarks:
     *   依頼元中継系会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_KAISHA
     *
     * @mbg.generated
     */
    private String cdKaisha;

    /**
     * Database Column Remarks:
     *   中間報告要否コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_CHUKANHOKOKU
     *
     * @mbg.generated
     */
    private String cdChukanhokoku;

    /**
     * Database Column Remarks:
     *   公開基準コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_KOKAIKIJUN
     *
     * @mbg.generated
     */
    private String cdKokaikijun;

    /**
     * Database Column Remarks:
     *   公開基準グループコード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_GROUP
     *
     * @mbg.generated
     */
    private String cdGroup;

    /**
     * Database Column Remarks:
     *   お客様名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.KJ_OKYAKU
     *
     * @mbg.generated
     */
    private String kjOkyaku;

    /**
     * Database Column Remarks:
     *   契約者名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.KJ_KEIYAKUSHA
     *
     * @mbg.generated
     */
    private String kjKeiyakusha;

    /**
     * Database Column Remarks:
     *   現地担当者への周知者(部署名)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.KJ_GS_BUSHO
     *
     * @mbg.generated
     */
    private String kjGsBusho;

    /**
     * Database Column Remarks:
     *   現地担当者への周知者(担当者名)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.KJ_GS_TANTO
     *
     * @mbg.generated
     */
    private String kjGsTanto;

    /**
     * Database Column Remarks:
     *   現地担当者への周知者(連絡先(Tel))
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.DT_GS_TEL
     *
     * @mbg.generated
     */
    private String dtGsTel;

    /**
     * Database Column Remarks:
     *   サービス名コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_SERVICE
     *
     * @mbg.generated
     */
    private String cdService;

    /**
     * Database Column Remarks:
     *   要望事項
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.KJ_YOBO
     *
     * @mbg.generated
     */
    private String kjYobo;

    /**
     * Database Column Remarks:
     *   商談状況
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_SHODAN
     *
     * @mbg.generated
     */
    private String cdShodan;

    /**
     * Database Column Remarks:
     *   一時保存ー契約者名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.TP_KJ_KEIYAKUSHA
     *
     * @mbg.generated
     */
    private String tpKjKeiyakusha;

    /**
     * Database Column Remarks:
     *   一時保存ー現地担当者への周知者(部署名)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.TP_KJ_GS_BUSHO
     *
     * @mbg.generated
     */
    private String tpKjGsBusho;

    /**
     * Database Column Remarks:
     *   一時保存ー現地担当者への周知者(担当者名)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.TP_KJ_GS_TANTO
     *
     * @mbg.generated
     */
    private String tpKjGsTanto;

    /**
     * Database Column Remarks:
     *   一時保存ー現地担当者への周知者(連絡先(Tel))
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.TP_DT_GS_TEL
     *
     * @mbg.generated
     */
    private String tpDtGsTel;

    /**
     * Database Column Remarks:
     *   ASG件名ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_ASGKENMEI
     *
     * @mbg.generated
     */
    private String cdAsgkenmei;

    /**
     * Database Column Remarks:
     *   ASG件名ID発行日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.TM_ASGKENMEI
     *
     * @mbg.generated
     */
    private LocalDateTime tmAsgkenmei;

    /**
     * Database Column Remarks:
     *   受逸注区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_JUCHU
     *
     * @mbg.generated
     */
    private String cdJuchu;

    /**
     * Database Column Remarks:
     *   件名保存状態区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_HOZONJOTAI
     *
     * @mbg.generated
     */
    private String cdHozonjotai;

    /**
     * Database Column Remarks:
     *   調査依頼区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_IRAI
     *
     * @mbg.generated
     */
    private String cdIrai;

    /**
     * Database Column Remarks:
     *   机上調査区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_KIJO
     *
     * @mbg.generated
     */
    private String cdKijo;

    /**
     * Database Column Remarks:
     *   最終更新会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_LU_KAISHA
     *
     * @mbg.generated
     */
    private String cdLuKaisha;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.CD_LU_USER
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.TM_LU
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * Database Column Remarks:
     *   営業担当者(部署名)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.KJ_EIGYO_BUSHO
     *
     * @mbg.generated
     */
    private String kjEigyoBusho;

    /**
     * Database Column Remarks:
     *   営業担当者(氏名)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.KJ_EIGYO_TANTO
     *
     * @mbg.generated
     */
    private String kjEigyoTanto;

    /**
     * Database Column Remarks:
     *   営業担当者(連絡先(TEL))
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KENMEI.DT_EIGYO_TEL
     *
     * @mbg.generated
     */
    private String dtEigyoTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_KENMEI
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}