package com.asg.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TT_KIJO
 */
@Data
public class TtKijo implements Serializable {
    /**
     * Database Column Remarks:
     *   内部件名ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KENMEI
     *
     * @mbg.generated
     */
    private String cdKenmei;

    /**
     * Database Column Remarks:
     *   回線ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KAISEN
     *
     * @mbg.generated
     */
    private String cdKaisen;

    /**
     * Database Column Remarks:
     *   開通希望区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KAITSUKIBO
     *
     * @mbg.generated
     */
    private String cdKaitsukibo;

    /**
     * Database Column Remarks:
     *   開通希望日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.YMD_KAITSUKIBO
     *
     * @mbg.generated
     */
    private LocalDateTime ymdKaitsukibo;

    /**
     * Database Column Remarks:
     *   事業所名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_JIGYOSHO
     *
     * @mbg.generated
     */
    private String kjJigyosho;

    /**
     * Database Column Remarks:
     *   都道府県コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KEN
     *
     * @mbg.generated
     */
    private String cdKen;

    /**
     * Database Column Remarks:
     *   住所
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_JUSHO
     *
     * @mbg.generated
     */
    private String kjJusho;

    /**
     * Database Column Remarks:
     *   ビル名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_BUILDING
     *
     * @mbg.generated
     */
    private String kjBuilding;

    /**
     * Database Column Remarks:
     *   フロア数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_FLOOR
     *
     * @mbg.generated
     */
    private String kjFloor;

    /**
     * Database Column Remarks:
     *   アクセス種別コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_ACCESSSHU
     *
     * @mbg.generated
     */
    private String cdAccessshu;

    /**
     * Database Column Remarks:
     *   アクセス品目コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_ACCESSHIN
     *
     * @mbg.generated
     */
    private String cdAccesshin;

    /**
     * Database Column Remarks:
     *   備考(中継系＝＞備考)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_BIKO1
     *
     * @mbg.generated
     */
    private String kjBiko1;

    /**
     * Database Column Remarks:
     *   対象事業者コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_JIGYOSHA
     *
     * @mbg.generated
     */
    private String cdJigyosha;

    /**
     * Database Column Remarks:
     *   提供可否コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_TEIKYOKAHI
     *
     * @mbg.generated
     */
    private String cdTeikyokahi;

    /**
     * Database Column Remarks:
     *   POI名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_POI
     *
     * @mbg.generated
     */
    private String kjPoi;

    /**
     * Database Column Remarks:
     *   収容局名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_KYOKU
     *
     * @mbg.generated
     */
    private String kjKyoku;

    /**
     * Database Column Remarks:
     *   距離区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KYORI
     *
     * @mbg.generated
     */
    private String cdKyori;

    /**
     * Database Column Remarks:
     *   見做しPOI名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_MN_POI
     *
     * @mbg.generated
     */
    private String kjMnPoi;

    /**
     * Database Column Remarks:
     *   見做し距離区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_MN_KYORI
     *
     * @mbg.generated
     */
    private String cdMnKyori;

    /**
     * Database Column Remarks:
     *   入線状況区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_NYUSEN
     *
     * @mbg.generated
     */
    private String cdNyusen;

    /**
     * Database Column Remarks:
     *   納期(申込書受領後)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_NOKI
     *
     * @mbg.generated
     */
    private String cdNoki;

    /**
     * Database Column Remarks:
     *   終点(CWC-POP)POP入線状況
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_NYUSEN_END
     *
     * @mbg.generated
     */
    private String cdNyusenEnd;

    /**
     * Database Column Remarks:
     *   MA内/外入力要否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_MAYOUHI
     *
     * @mbg.generated
     */
    private String cdMayouhi;

    /**
     * Database Column Remarks:
     *   距離(起点～終点)MA内/外
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KS_KYORI
     *
     * @mbg.generated
     */
    private String cdKsKyori;

    /**
     * Database Column Remarks:
     *   距離(起点～終点)実距離(km)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.DT_KS_KYORI
     *
     * @mbg.generated
     */
    private String dtKsKyori;

    /**
     * Database Column Remarks:
     *   回線使用料
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.NM_KAISEN
     *
     * @mbg.generated
     */
    private Integer nmKaisen;

    /**
     * Database Column Remarks:
     *   機器使用料
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.NM_KIKI
     *
     * @mbg.generated
     */
    private Integer nmKiki;

    /**
     * Database Column Remarks:
     *   提供エリア内外区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_TEIKYOAREA
     *
     * @mbg.generated
     */
    private String cdTeikyoarea;

    /**
     * Database Column Remarks:
     *   備考(地域系＝＞中継系)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.KJ_BIKO2
     *
     * @mbg.generated
     */
    private String kjBiko2;

    /**
     * Database Column Remarks:
     *   一時保存-開通希望区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_KAITSUKIBO
     *
     * @mbg.generated
     */
    private String tpCdKaitsukibo;

    /**
     * Database Column Remarks:
     *   一時保存-開通希望日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_YMD_KAITSUKIBO
     *
     * @mbg.generated
     */
    private LocalDateTime tpYmdKaitsukibo;

    /**
     * Database Column Remarks:
     *   一時保存-事業所名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_JIGYOSHO
     *
     * @mbg.generated
     */
    private String tpKjJigyosho;

    /**
     * Database Column Remarks:
     *   一時保存-都道府県コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_KEN
     *
     * @mbg.generated
     */
    private String tpCdKen;

    /**
     * Database Column Remarks:
     *   一時保存-住所
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_JUSHO
     *
     * @mbg.generated
     */
    private String tpKjJusho;

    /**
     * Database Column Remarks:
     *   一時保存-ビル名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_BUILDING
     *
     * @mbg.generated
     */
    private String tpKjBuilding;

    /**
     * Database Column Remarks:
     *   一時保存-フロア数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_FLOOR
     *
     * @mbg.generated
     */
    private String tpKjFloor;

    /**
     * Database Column Remarks:
     *   一時保存-アクセス種別コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_ACCESSSHU
     *
     * @mbg.generated
     */
    private String tpCdAccessshu;

    /**
     * Database Column Remarks:
     *   一時保存-アクセス品目コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_ACCESSHIN
     *
     * @mbg.generated
     */
    private String tpCdAccesshin;

    /**
     * Database Column Remarks:
     *   一時保存-備考(中継系＝＞備考)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_BIKO1
     *
     * @mbg.generated
     */
    private String tpKjBiko1;

    /**
     * Database Column Remarks:
     *   一時保存-対象事業者コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_JIGYOSHA
     *
     * @mbg.generated
     */
    private String tpCdJigyosha;

    /**
     * Database Column Remarks:
     *   一時保存-提供可否コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_TEIKYOKAHI
     *
     * @mbg.generated
     */
    private String tpCdTeikyokahi;

    /**
     * Database Column Remarks:
     *   一時保存-POI名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_POI
     *
     * @mbg.generated
     */
    private String tpKjPoi;

    /**
     * Database Column Remarks:
     *   一時保存-収容局名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_KYOKU
     *
     * @mbg.generated
     */
    private String tpKjKyoku;

    /**
     * Database Column Remarks:
     *   一時保存-距離区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_KYORI
     *
     * @mbg.generated
     */
    private String tpCdKyori;

    /**
     * Database Column Remarks:
     *   一時保存-見做しPOI名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_MN_POI
     *
     * @mbg.generated
     */
    private String tpKjMnPoi;

    /**
     * Database Column Remarks:
     *   一時保存-見做し距離区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_MN_KYORI
     *
     * @mbg.generated
     */
    private String tpCdMnKyori;

    /**
     * Database Column Remarks:
     *   一時保存-入線状況区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_NYUSEN
     *
     * @mbg.generated
     */
    private String tpCdNyusen;

    /**
     * Database Column Remarks:
     *   一時保存-納期(申込書受領後)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_NOKI
     *
     * @mbg.generated
     */
    private String tpCdNoki;

    /**
     * Database Column Remarks:
     *   一時保存-終点(CWC-POP)POP入線状況
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_NYUSEN_END
     *
     * @mbg.generated
     */
    private String tpCdNyusenEnd;

    /**
     * Database Column Remarks:
     *   一時保存-MA内/外入力要否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_MAYOUHI
     *
     * @mbg.generated
     */
    private String tpCdMayouhi;

    /**
     * Database Column Remarks:
     *   一時保存-距離(起点～終点)MA内/外
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_KS_KYORI
     *
     * @mbg.generated
     */
    private String tpCdKsKyori;

    /**
     * Database Column Remarks:
     *   一時保存-距離(起点～終点)実距離(km)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_DT_KS_KYORI
     *
     * @mbg.generated
     */
    private String tpDtKsKyori;

    /**
     * Database Column Remarks:
     *   一時保存-回線使用料
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_NM_KAISEN
     *
     * @mbg.generated
     */
    private Integer tpNmKaisen;

    /**
     * Database Column Remarks:
     *   一時保存-機器使用料
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_NM_KIKI
     *
     * @mbg.generated
     */
    private Integer tpNmKiki;

    /**
     * Database Column Remarks:
     *   一時保存-提供エリア内外区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_TEIKYOAREA
     *
     * @mbg.generated
     */
    private String tpCdTeikyoarea;

    /**
     * Database Column Remarks:
     *   一時保存-備考(地域系＝＞中継系)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_KJ_BIKO2
     *
     * @mbg.generated
     */
    private String tpKjBiko2;

    /**
     * Database Column Remarks:
     *   状態区分-開通希望区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_KAITSUKIBO
     *
     * @mbg.generated
     */
    private String cdCdKaitsukibo;

    /**
     * Database Column Remarks:
     *   状態区分-開通希望日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_YMD_KAITSUKIBO
     *
     * @mbg.generated
     */
    private String cdYmdKaitsukibo;

    /**
     * Database Column Remarks:
     *   状態区分-事業所名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_JIGYOSHO
     *
     * @mbg.generated
     */
    private String cdKjJigyosho;

    /**
     * Database Column Remarks:
     *   状態区分-都道府県コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_KEN
     *
     * @mbg.generated
     */
    private String cdCdKen;

    /**
     * Database Column Remarks:
     *   状態区分-住所
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_JUSHO
     *
     * @mbg.generated
     */
    private String cdKjJusho;

    /**
     * Database Column Remarks:
     *   状態区分-ビル名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_BUILDING
     *
     * @mbg.generated
     */
    private String cdKjBuilding;

    /**
     * Database Column Remarks:
     *   状態区分-フロア数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_FLOOR
     *
     * @mbg.generated
     */
    private String cdKjFloor;

    /**
     * Database Column Remarks:
     *   状態区分-アクセス種別コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_ACCESSSHU
     *
     * @mbg.generated
     */
    private String cdCdAccessshu;

    /**
     * Database Column Remarks:
     *   状態区分-アクセス品目コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_ACCESSHIN
     *
     * @mbg.generated
     */
    private String cdCdAccesshin;

    /**
     * Database Column Remarks:
     *   状態区分-備考(中継系＝＞備考)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_BIKO1
     *
     * @mbg.generated
     */
    private String cdKjBiko1;

    /**
     * Database Column Remarks:
     *   状態区分-対象事業者コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_JIGYOSHA
     *
     * @mbg.generated
     */
    private String cdCdJigyosha;

    /**
     * Database Column Remarks:
     *   状態区分-提供可否コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_TEIKYOKAHI
     *
     * @mbg.generated
     */
    private String cdCdTeikyokahi;

    /**
     * Database Column Remarks:
     *   状態区分-POI名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_POI
     *
     * @mbg.generated
     */
    private String cdKjPoi;

    /**
     * Database Column Remarks:
     *   状態区分-収容局名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_KYOKU
     *
     * @mbg.generated
     */
    private String cdKjKyoku;

    /**
     * Database Column Remarks:
     *   状態区分-距離区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_KYORI
     *
     * @mbg.generated
     */
    private String cdCdKyori;

    /**
     * Database Column Remarks:
     *   状態区分-見做しPOI名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_MN_POI
     *
     * @mbg.generated
     */
    private String cdKjMnPoi;

    /**
     * Database Column Remarks:
     *   状態区分-見做し距離区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_MN_KYORI
     *
     * @mbg.generated
     */
    private String cdCdMnKyori;

    /**
     * Database Column Remarks:
     *   状態区分-入線状況区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_NYUSEN
     *
     * @mbg.generated
     */
    private String cdCdNyusen;

    /**
     * Database Column Remarks:
     *   状態区分-納期(申込書受領後)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_NOKI
     *
     * @mbg.generated
     */
    private String cdCdNoki;

    /**
     * Database Column Remarks:
     *   状態区分-終点(CWC-POP)POP入線状況
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_NYUSEN_END
     *
     * @mbg.generated
     */
    private String cdCdNyusenEnd;

    /**
     * Database Column Remarks:
     *   状態区分-MA内/外入力要否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_MAYOUHI
     *
     * @mbg.generated
     */
    private String cdCdMayouhi;

    /**
     * Database Column Remarks:
     *   状態区分-距離(起点～終点)MA内/外
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_KS_KYORI
     *
     * @mbg.generated
     */
    private String cdCdKsKyori;

    /**
     * Database Column Remarks:
     *   状態区分-距離(起点～終点)実距離(km)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_DT_KS_KYORI
     *
     * @mbg.generated
     */
    private String cdDtKsKyori;

    /**
     * Database Column Remarks:
     *   状態区分-回線使用料
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_NM_KAISEN
     *
     * @mbg.generated
     */
    private String cdNmKaisen;

    /**
     * Database Column Remarks:
     *   状態区分-機器使用料
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_NM_KIKI
     *
     * @mbg.generated
     */
    private String cdNmKiki;

    /**
     * Database Column Remarks:
     *   状態区分-提供エリア内外区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_TEIKYOAREA
     *
     * @mbg.generated
     */
    private String cdCdTeikyoarea;

    /**
     * Database Column Remarks:
     *   状態区分-備考(地域系＝＞中継系)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_KJ_BIKO2
     *
     * @mbg.generated
     */
    private String cdKjBiko2;

    /**
     * Database Column Remarks:
     *   ASG件名ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_ASGKENMEI
     *
     * @mbg.generated
     */
    private String cdAsgkenmei;

    /**
     * Database Column Remarks:
     *   最終更新者会社コード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_LU_KAISHA
     *
     * @mbg.generated
     */
    private String cdLuKaisha;

    /**
     * Database Column Remarks:
     *   最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_LU_USER
     *
     * @mbg.generated
     */
    private String cdLuUser;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TM_LU
     *
     * @mbg.generated
     */
    private LocalDateTime tmLu;

    /**
     * Database Column Remarks:
     *   中継系最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_LU_CHUKEI_USER
     *
     * @mbg.generated
     */
    private String cdLuChukeiUser;

    /**
     * Database Column Remarks:
     *   中継系最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TM_LU_CHUKEI
     *
     * @mbg.generated
     */
    private LocalDateTime tmLuChukei;

    /**
     * Database Column Remarks:
     *   地域系最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_LU_CHIIKI_USER
     *
     * @mbg.generated
     */
    private String cdLuChiikiUser;

    /**
     * Database Column Remarks:
     *   地域系最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TM_LU_CHIIKI
     *
     * @mbg.generated
     */
    private LocalDateTime tmLuChiiki;

    /**
     * Database Column Remarks:
     *   ASG最終更新者ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_LU_ASG_USER
     *
     * @mbg.generated
     */
    private String cdLuAsgUser;

    /**
     * Database Column Remarks:
     *   ASG最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TM_LU_ASG
     *
     * @mbg.generated
     */
    private LocalDateTime tmLuAsg;

    /**
     * Database Column Remarks:
     *   回線状態区分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_JT
     *
     * @mbg.generated
     */
    private String cdJt;

    /**
     * Database Column Remarks:
     *   定型コメント
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_COMMENT
     *
     * @mbg.generated
     */
    private String cdComment;

    /**
     * Database Column Remarks:
     *   一時保存-定型コメント
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.TP_CD_COMMENT
     *
     * @mbg.generated
     */
    private String tpCdComment;

    /**
     * Database Column Remarks:
     *   状態区分-定型コメント
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_CD_COMMENT
     *
     * @mbg.generated
     */
    private String cdCdComment;

    /**
     * Database Column Remarks:
     *   現調依頼メール
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_KIJO.CD_GENCHI_IRAI_MAIL
     *
     * @mbg.generated
     */
    private String cdGenchiIraiMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_KIJO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}